

    typedef [helpcontext(IDH_ENUMTYPES), uuid(E4DDB2F7-2523-41F3-8301-1B6F3D12A322)] [v1_enum] enum ZcBoolean
    {
        
        zcFalse = 0,
        zcTrue = 1
    } ZcBoolean;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(74ADFD66-2640-4B93-A70F-C1E9FD91B15C)] [v1_enum] enum ZcOnOff
    {
        
        zcOff = 0,
        zcOn = 1
    } ZcOnOff;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(CF344D9E-6A39-430F-B447-D7547BACA32C)] [v1_enum] enum ZcEntityName
    {
        
        zc3dFace = 1,
        zc3dPolyline = 2,
        zc3dSolid = 3,
        zcArc = 4,
        zcAttribute = 5,
        zcAttributeReference = 6,
        zcBlockReference = 7,
        zcCircle = 8,
        zcDimAligned = 9,
        zcDimAngular = 10,

        zcDimDiametric = 12,
        zcDimOrdinate = 13,
        zcDimRadial = 14,
        zcDimRotated = 15,
        zcEllipse = 16,
        zcHatch = 17,
        zcLeader = 18,
        zcLine = 19,

        zcMtext = 21,
        zcPoint = 22,
        zcPolyline = 23,
        zcPolylineLight = 24,
        zcPolymesh = 25,
        zcRaster = 26,
        zcRay = 27,
        zcRegion = 28,
        zcShape = 29,
        zcSolid = 30,
        zcSpline = 31,
        zcText = 32,
        zcTolerance = 33,
        zcTrace = 34,
        zcPViewport = 35,
        zcXline = 36,
        zcGroup = 37,
        zcMInsertBlock = 38,
        zcPolyfaceMesh = 39,
        zcMLine = 40,
        zcDim3PointAngular = 41,
        zcExternalReference = 42,
        zcTable = 43,
        zcDimArcLength = 44,
		zcDimRadialLarge = 45,
        zcDwfUnderlay = 46,
        zcDgnUnderlay = 47,
        zcMLeader = 48
    } ZcEntityName;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(918A27ED-8350-422F-9BD0-DB75EC0E4F0F)] [v1_enum] enum ZcActiveSpace
    {
        
        zcPaperSpace = 0,
        zcModelSpace = 1
    } ZcActiveSpace;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(9EA09DA4-5A57-4ACA-AC5E-26C9E1E96ECF)] [v1_enum] enum ZcKeyboardAccelerator
    {
        
        zcPreferenceClassic = 0,
        zcPreferenceCustom = 1
    } ZcKeyboardAccelerator;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(587275CB-5CDD-41CA-B893-9B6C5B8C620E)] [v1_enum] enum ZcPlotOrientation
    {
        
        zcPlotOrientationPortrait = 0,
        zcPlotOrientationLandscape = 1
    } ZcPlotOrientation;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(91655BE6-318D-4F17-AB1A-17A90FDB02D5)] [v1_enum] enum ZcColor
    {
        
        [helpstring("Color Byblock.")]
        zcByBlock = 0,
        [helpstring("Color Red.")]
        zcRed = 1,
        [helpstring("Color Yellow.")]
        zcYellow = 2,
        [helpstring("Color Green.")]
        zcGreen = 3,
        [helpstring("Color Cyan.")]
        zcCyan = 4,
        [helpstring("Color Blue.")]
        zcBlue = 5,
        [helpstring("Color Magenta.")]
        zcMagenta = 6,
        [helpstring("Color White.")]
        zcWhite = 7,
        [helpstring("Color Bylayer.")]
        zcByLayer = 256
    } ZcColor;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(6C96CBEC-1D4C-4542-969B-86F669FEC6C9)] [v1_enum] enum ZcAttachmentPoint
    {
        
        zcAttachmentPointTopLeft = 1,
        zcAttachmentPointTopCenter = 2,
        zcAttachmentPointTopRight = 3,
        zcAttachmentPointMiddleLeft = 4,
        zcAttachmentPointMiddleCenter = 5,
        zcAttachmentPointMiddleRight = 6,
        zcAttachmentPointBottomLeft = 7,
        zcAttachmentPointBottomCenter = 8,
        zcAttachmentPointBottomRight = 9
    } ZcAttachmentPoint;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(318B9D08-54E7-42DD-8478-204D20D68A91)] [v1_enum] enum ZcDrawingDirection
    {
        
        zcLeftToRight = 1,
        zcRightToLeft = 2,
        zcTopToBottom = 3,
        zcBottomToTop = 4,
        zcByStyle     = 5
    } ZcDrawingDirection;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(799452AA-AC81-491C-A086-9403B70A20C6)] [v1_enum] enum ZcLeaderType
    {
        
        zcLineNoArrow = 0,
        zcSplineNoArrow = 1,
        zcLineWithArrow = 2,
        zcSplineWithArrow = 3
    } ZcLeaderType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(55A55AB0-C6AD-4CCF-A3DD-D71A72A452D1)] [v1_enum] enum ZcAttributeMode
    {
        
        zcAttributeModeNormal = 0,
        zcAttributeModeInvisible = 1,
        zcAttributeModeConstant = 2,
        zcAttributeModeVerify = 4,
        zcAttributeModePreset = 8,
        zcAttributeModeLockPosition = 16,
        zcAttributeModeMultipleLine = 32
    } ZcAttributeMode;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(3202A1E2-C0A1-4A52-8376-41B678521F52)] [v1_enum] enum ZcHorizontalAlignment
    {
        
        zcHorizontalAlignmentLeft = 0,
        zcHorizontalAlignmentCenter = 1,
        zcHorizontalAlignmentRight = 2,
        zcHorizontalAlignmentAligned = 3,
        zcHorizontalAlignmentMiddle = 4,
        zcHorizontalAlignmentFit = 5
    } ZcHorizontalAlignment;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(6FAE9739-700A-4A81-8252-80E282E77D2E)] [v1_enum] enum ZcVerticalAlignment
    {
        
        zcVerticalAlignmentBaseline = 0,
        zcVerticalAlignmentBottom = 1,
        zcVerticalAlignmentMiddle = 2,
        zcVerticalAlignmentTop = 3
    } ZcVerticalAlignment;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(A617C48C-FB6E-4DD1-8856-9338F894D66C)] [v1_enum] enum ZcTextGenerationFlag
    {
        
        zcTextFlagBackward = 2,
        zcTextFlagUpsideDown = 4
    } ZcTextGenerationFlag;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(F25593CC-073C-48BC-A4C0-2F9039E51E70)] [v1_enum] enum ZcSelect
    {
        
        zcSelectionSetWindow = 0,
        zcSelectionSetCrossing = 1,
        zcSelectionSetFence = 2,
        zcSelectionSetPrevious = 3,
        zcSelectionSetLast = 4,
        zcSelectionSetAll = 5,
        zcSelectionSetWindowPolygon = 6,
        zcSelectionSetCrossingPolygon = 7
    } ZcSelect;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(5DA89BB3-044C-47DC-944A-D9A27ECB2260)] [v1_enum] enum ZcPatternType
    {

        zcHatchPatternTypeUserDefined = 0,
        zcHatchPatternTypePreDefined = 1,
        zcHatchPatternTypeCustomDefined = 2
    } ZcPatternType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(42F195AC-9436-46DB-97FC-41A159A103B5)] [v1_enum] enum ZcLoopType
    {
        
        zcHatchLoopTypeDefault = 0,
        zcHatchLoopTypeExternal = 1,
        zcHatchLoopTypePolyline = 2,
        zcHatchLoopTypeDerived = 4,
        zcHatchLoopTypeTextbox = 8
    } ZcLoopType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(6EAEA175-606B-4C10-A37C-13BF7C560F42)] [v1_enum] enum ZcHatchStyle
    {
        zcHatchStyleNormal = 0,
        zcHatchStyleOuter = 1,
        zcHatchStyleIgnore = 2 
    } ZcHatchStyle;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(78277E24-3CA3-4C94-AED8-CE70174C9B71)] [v1_enum] enum ZcPolylineType
    {
        
        zcSimplePoly = 0,
        zcFitCurvePoly = 1,
        zcQuadSplinePoly = 2,
        zcCubicSplinePoly = 3
    } ZcPolylineType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(0B899271-C764-465C-B5AC-9775DDC3965D)] [v1_enum] enum Zc3DPolylineType
    {
        
        zcSimple3DPoly = 0,
        zcQuadSpline3DPoly = 1,
        zcCubicSpline3DPoly = 2
    } Zc3DPolylineType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(2AD465F1-0B3F-4FDC-8791-0CA38FCB46FC)] [v1_enum] enum ZcViewportSplitType
    {
        
        zcViewport2Horizontal = 0,
        zcViewport2Vertical = 1,
        zcViewport3Left = 2,
        zcViewport3Right = 3,
        zcViewport3Horizontal = 4,
        zcViewport3Vertical = 5,
        zcViewport3Above = 6,
        zcViewport3Below = 7,
        zcViewport4 = 8
    } ZcViewportSplitType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(F270F984-F927-414F-BA3E-22A2DC3358BF)] [v1_enum] enum ZcRegenType
    {
        
        zcActiveViewport = 0,
        zcAllViewports = 1
    } ZcRegenType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(27550F17-937C-42B4-8B49-270096F8021A)] [v1_enum] enum ZcBooleanType
    {
        
        zcUnion = 0,
        zcIntersection = 1,
        zcSubtraction = 2
    } ZcBooleanType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(9D21FC53-EFC1-4337-91FA-2241ECCB360B)] [v1_enum] enum ZcExtendOption
    {
        
        zcExtendNone = 0,
        zcExtendThisEntity = 1,
        zcExtendOtherEntity = 2,
        zcExtendBoth = 3
    } ZcExtendOption;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(E2DC866F-EF43-4ECC-B1D6-6C39CA2C6640)] [v1_enum] enum ZcAngleUnits
    {
        
        zcDegrees = 0,
        zcDegreeMinuteSeconds = 1,
        zcGrads = 2,
        zcRadians = 3
    } ZcAngleUnits;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(C517F337-C37C-442C-9931-E00296BEEE26)] [v1_enum] enum ZcUnits
    {
        
        zcDefaultUnits = -1,
        zcScientific = 1,
        zcDecimal = 2,
        zcEngineering = 3,
        zcArchitectural = 4,
        zcFractional = 5
    } ZcUnits;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(047C68C9-6BB0-498D-AC16-F6C441F1A91C)] [v1_enum] enum ZcCoordinateSystem
    {
        
        zcWorld = 0,
        zcUCS = 1,
        zcDisplayDCS = 2,
        zcPaperSpaceDCS = 3,
        zcOCS = 4,
    } ZcCoordinateSystem;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(C6594E6D-FEED-48FE-9D92-9A44A7320234)] [v1_enum] enum ZcMeasurementUnits
    {
        
        zcEnglish = 0,
        zcMetric = 1,
    } ZcMeasurementUnits;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(C25EF5AF-3B5C-4AEC-BC29-0DE3E88203A3)] [v1_enum] enum ZcXRefDemandLoad
    {
        
        zcDemandLoadDisabled = 0,
        zcDemandLoadEnabled = 1,
        zcDemandLoadEnabledWithCopy = 2
    } ZcXRefDemandLoad;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(084662AE-A45A-44BB-A879-8BA4A053031E)] [v1_enum] enum ZcPreviewMode
    {
        
        zcPartialPreview = 0,
        zcFullPreview = 1
    } ZcPreviewMode;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(7B3CBE8A-BB7F-410A-8627-CC6B69484CD5)] [v1_enum] enum ZcPolymeshType
    {
        
        zcSimpleMesh = 0,
        zcQuadSurfaceMesh = 5,
        zcCubicSurfaceMesh = 6,
        zcBezierSurfaceMesh = 8
    } ZcPolymeshType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(D91A2947-A374-47F3-954A-1F7FC0B8F3DD)] [v1_enum] enum ZcZoomScaleType
    {
        
        zcZoomScaledAbsolute =  0,
        zcZoomScaledRelative =  1,
        zcZoomScaledRelativePSpace =  2
    } ZcZoomScaleType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(4DBDCF77-F985-4A73-B057-F7ECF798B9A7)] [v1_enum] enum ZcDragDisplayMode
    {
        
        zcDragDoNotDisplay = 0,
        zcDragDisplayOnRequest = 1,
        zcDragDisplayAutomatically = 2
    } ZcDragDisplayMode;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(BC1C7F50-E4FA-4286-997B-760FBD4D70F1)] [v1_enum] enum ZcZRXDemandLoad
    {
        
        zcDemanLoadDisable = 0,
        zcDemandLoadOnObjectDetect = 1,
        zcDemandLoadCmdInvoke    = 2
    } ZcZRXDemandLoad;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(DFA98568-9E45-417D-847F-BF990BF9A65B)] [v1_enum] enum ZcTextFontStyle
    {
        zcFontRegular = 0,
        zcFontItalic = 1,
        zcFontBold = 2,
        zcFontBoldItalic = 3
    } ZcTextFontStyle;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(8A76565F-67E8-4FF8-961F-398BE2ACAE3D)] [v1_enum] enum ZcProxyImage
    {
        zcProxyNotShow = 0,
        zcProxyShow = 1,
        zcProxyBoundingBox = 2
    } ZcProxyImage;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(7D61735A-B753-4E6A-91AC-716BF1DD4815)] [v1_enum] enum ZcKeyboardPriority
    {
        zcKeyboardRunningObjSnap = 0,
        zcKeyboardEntry = 1,
        zcKeyboardEntryExceptScripts = 2
    } ZcKeyboardPriority;

    const LPSTR zcAmericanEnglish = "enu";
    const LPSTR zcAustralianEnglish = "ena";
    const LPSTR zcBritishEnglishIse = "ens";
    const LPSTR zcBritishEnglishIze = "enz";
    const LPSTR zcCatalan = "ca";
    const LPSTR zcCzech = "cs";
    const LPSTR zcDanish = "da";
    const LPSTR zcDutchPrim = "nl";
    const LPSTR zcDutchSec = "nls";
    const LPSTR zcFinnish = "fi";
    const LPSTR zcFrenchUnaccentCap = "fr";
    const LPSTR zcFrenchAccentCap = "fra";
    const LPSTR zcGermanScharfesS = "de";
    const LPSTR zcGermanDoppleS = "ded";
    const LPSTR zcItalian = "it";
    const LPSTR zcNorwegianBokmal = "no";
    const LPSTR zcNorwegianNynorsk = "non";
    const LPSTR zcPortugueseIberian = "pt";
    const LPSTR zcPortugueseBrazilian = "ptb";
    const LPSTR zcRussianInfrequentIo = "ru";
    const LPSTR zcRussianFrequentIo = "rui";
    const LPSTR zcSpanishUnaccentCap = "es";
    const LPSTR zcSpanishAccentCap = "esa";
    const LPSTR zcSwedish = "sv";

    typedef [helpcontext(IDH_ENUMTYPES), uuid(4BC6D2FE-C3A4-494F-B8FF-3FC5C348CEEE)] [v1_enum] enum ZcMenuGroupType
    {
        zcBaseMenuGroup = 0,
        zcPartialMenuGroup = 1
    } ZcMenuGroupType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(CA86EB70-F967-4496-80E4-B9D6785707B3)] [v1_enum] enum ZcMenuFileType
    {
        zcMenuFileCompiled = 0,
        zcMenuFileSource = 1
    } ZcMenuFileType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(8D2C592F-C2E0-413A-B4EC-DF2545AEFE4A)] [v1_enum] enum ZcMenuItemType
    {
        zcMenuItem = 0,
        zcMenuSeparator = 1,
        zcMenuSubMenu = 2
    } ZcMenuItemType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(CB41EFC9-DE52-44A8-8A17-3D19E98EA44E)] [v1_enum] enum ZcToolbarItemType
    {
        zcToolbarButton = 0,
        zcToolbarSeparator = 1,
        zcToolbarControl = 2,
        zcToolbarFlyout = 3
    } ZcToolbarItemType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(78F2FB7B-7C73-41D6-96F6-F630E02CD73A)] [v1_enum] enum ZcToolbarDockStatus
    {
        zcToolbarDockTop = 0,
        zcToolbarDockBottom = 1,
        zcToolbarDockLeft = 2,
        zcToolbarDockRight = 3,
        zcToolbarFloating = 4
    } ZcToolbarDockStatus;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(4EA2958C-3A1E-47F2-B57F-97A41AC622F2)] [v1_enum] enum ZcLineWeight
    { 
        zcLnWt000          =   0,
        zcLnWt005          =   5,
        zcLnWt009          =   9,
        zcLnWt013          =  13,
        zcLnWt015          =  15,
        zcLnWt018          =  18,
        zcLnWt020          =  20,
        zcLnWt025          =  25,
        zcLnWt030          =  30,
        zcLnWt035          =  35,
        zcLnWt040          =  40,
        zcLnWt050          =  50,
        zcLnWt053          =  53,
        zcLnWt060          =  60,
        zcLnWt070          =  70,
        zcLnWt080          =  80,
        zcLnWt090          =  90,
        zcLnWt100          = 100,
        zcLnWt106          = 106,
        zcLnWt120          = 120,
        zcLnWt140          = 140,
        zcLnWt158          = 158,
        zcLnWt200          = 200,
        zcLnWt211          = 211,
        zcLnWtByLayer      = -1,
        zcLnWtByBlock      = -2,
        zcLnWtByLwDefault  = -3
    } ZcLineWeight;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(FA122268-15D5-41C7-9F4A-5999C7D7AB8E)] [v1_enum] enum ZcWindowState
    {
        zcNorm = 1,
        zcMin,
        zcMax
    } ZcWindowState;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(ACE4C627-318E-46B3-B7C4-1293883A7366)] [v1_enum] enum ZcPlotPaperUnits
    {
        zcInches = 0,
        zcMillimeters,
        zcPixels
    } ZcPlotPaperUnits;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(400EF11E-D456-4BFB-9108-0D9959E166F7)] [v1_enum] enum ZcPlotRotation
    {
        zc0degrees = 0,
        zc90degrees,
        zc180degrees,
        zc270degrees
    } ZcPlotRotation;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(3762077A-3F65-424B-8ABD-5EF191F26D13)] [v1_enum] enum ZcPlotType
    {
        zcDisplay = 0,
        zcExtents,
        zcLimits,
        zcView,
        zcWindow,
        zcLayout
    } ZcPlotType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(27462081-E55B-4FAC-97B9-3A5A96D51ACC)] [v1_enum] enum ZcPlotScale
    {
        zcScaleToFit = 0,              
        zc1_128in_1ft,                 
        zc1_64in_1ft,                  
        zc1_32in_1ft,                  
        zc1_16in_1ft,                  
        zc3_32in_1ft,                  
        zc1_8in_1ft,                   
        zc3_16in_1ft,                  
        zc1_4in_1ft,                   
        zc3_8in_1ft,                   
        zc1_2in_1ft,                   
        zc3_4in_1ft,                   
        zc1in_1ft,                     
        zc3in_1ft,                     
        zc6in_1ft,                     
        zc1ft_1ft,                     
        zc1_1,                         
        zc1_2,                         
        zc1_4,
		zc1_5,
        zc1_8,                         
        zc1_10,                        
        zc1_16,                        
        zc1_20,                        
        zc1_30,                        
        zc1_40,                        
        zc1_50,                        
        zc1_100,                       
        zc2_1,                         
        zc4_1,                         
        zc8_1,                         
        zc10_1,                        
        zc100_1,                       
    } ZcPlotScale;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(DD33DB59-A06D-41B2-8574-AC7CBCFAD8A1)] [v1_enum] enum ZcAlignment
    {
        zcAlignmentLeft = 0,
        zcAlignmentCenter,
        zcAlignmentRight,
        zcAlignmentAligned,
        zcAlignmentMiddle,
        zcAlignmentFit,
        zcAlignmentTopLeft,
        zcAlignmentTopCenter,
        zcAlignmentTopRight,
        zcAlignmentMiddleLeft,
        zcAlignmentMiddleCenter,
        zcAlignmentMiddleRight,
        zcAlignmentBottomLeft,
        zcAlignmentBottomCenter,
        zcAlignmentBottomRight
    } ZcAlignment;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(8B2FC4C2-FBF3-4A41-809C-A98DBCF45E5D)] [public] ZcColor       ZCAD_COLOR;
    typedef [helpcontext(IDH_ENUMTYPES), uuid(1ABB07CA-C5C2-42F8-8B6D-3838DA696424)] [public] BSTR          ZCAD_LAYER;
    typedef [helpcontext(IDH_ENUMTYPES), uuid(9050699E-B7CC-4F48-A636-92EBA1DFA934)] [public] BSTR          ZCAD_LTYPE;
    typedef [helpcontext(IDH_ENUMTYPES), uuid(D21D356E-6F07-42DF-9DFC-EAFAC6393CDC)] [public] long          ZCAD_NULL;
    typedef [helpcontext(IDH_ENUMTYPES), uuid(9DA15F33-0F96-42AC-BA13-AECECE18BF3A)] [public] double        ZCAD_DISTANCE;
    typedef [helpcontext(IDH_ENUMTYPES), uuid(74D19576-D768-4D9B-A57D-C3A33B5D4A94)] [public] double        ZCAD_ANGLE;
    typedef [helpcontext(IDH_ENUMTYPES), uuid(E49A349D-C2DF-422D-9184-48F8B4E128CE)] [public] ZcLineWeight  ZCAD_LWEIGHT;
    typedef [helpcontext(IDH_ENUMTYPES), uuid(0AC6E833-B162-4848-821E-7D0152DED781)] [public] double        ZCAD_NOUNITS;
    typedef [helpcontext(IDH_ENUMTYPES), uuid(3B98C3E5-D140-4293-A42C-DF32A3297438)] [public] VARIANT       ZCAD_POINT;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(1B808687-4251-4228-890D-4F846367BC54)] [v1_enum] enum ZcLineSpacingStyle
    {
        
        zcLineSpacingStyleAtLeast = 1,
        zcLineSpacingStyleExactly = 2,
    } ZcLineSpacingStyle;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(8AED0DFE-BA87-45D6-8151-52701F5ECFCA)] [v1_enum] enum ZcDimPrecision
    {
        
        zcDimPrecisionZero = 0,
        zcDimPrecisionOne,
        zcDimPrecisionTwo,
        zcDimPrecisionThree,
        zcDimPrecisionFour,
        zcDimPrecisionFive,
        zcDimPrecisionSix,
        zcDimPrecisionSeven,
        zcDimPrecisionEight
    } ZcDimPrecision;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(26B5AC1E-D84B-4255-97D9-20A081014484)] [v1_enum] enum ZcDimUnits
    {
        
        zcDimScientific = 1,
        zcDimDecimal,
        zcDimEngineering,
        zcDimArchitecturalStacked,
        zcDimFractionalStacked,
        zcDimArchitectural,
        zcDimFractional,
        zcDimWindowsDesktop
    } ZcDimUnits;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(1465F1FB-49B6-4B73-AF75-25E1F3F8FECA)] [v1_enum] enum ZcDimLUnits
    {
        
        zcDimLScientific = 1,
        zcDimLDecimal,
        zcDimLEngineering,
        zcDimLArchitectural,
        zcDimLFractional,
        zcDimLWindowsDesktop
    } ZcDimLUnits;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(5DA8CCD6-2510-453C-B659-DC6CB31916C0)] [v1_enum] enum ZcDimArrowheadType
    {
        
        zcArrowDefault       = 0,
        zcArrowClosedBlank   = 1,
        zcArrowClosed        = 2,
        zcArrowDot           = 3,
        zcArrowArchTick      = 4,
        zcArrowOblique       = 5,    
        zcArrowOpen          = 6,
        zcArrowOrigin        = 7,
        zcArrowOrigin2       = 8,
        zcArrowOpen90        = 9,    
        zcArrowOpen30        = 10,
        zcArrowDotSmall      = 11,
        zcArrowDotBlank      = 12,
        zcArrowSmall         = 13,
        zcArrowBoxBlank      = 14,
        zcArrowBoxFilled     = 15,
        zcArrowDatumBlank    = 16,
        zcArrowDatumFilled   = 17,
        zcArrowIntegral      = 18,
        zcArrowNone          = 19,
        zcArrowUserDefined   = 20
    } ZcDimArrowheadType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(1C2F304D-5C25-4A10-BB38-8A1B5D59D46A)] [v1_enum] enum ZcDimCenterType
    {
        
        zcCenterMark = 0,
        zcCenterLine,
        zcCenterNone
    } ZcDimCenterType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(4854F7B6-0D14-4830-A43E-D60BE8297465)] [v1_enum] enum ZcDimFit
    {
        
        zcTextAndArrows = 0,
        zcArrowsOnly,
        zcTextOnly,
        zcBestFit
    } ZcDimFit;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(F7B8D2A9-C724-4621-9C93-E6509AB6C338)] [v1_enum] enum ZcDimFractionType
    {
        
        zcHorizontal = 0,
        zcDiagonal,
        zcNotStacked
    } ZcDimFractionType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(A643B964-6053-4051-9350-AE712E6B779A)] [v1_enum] enum ZcDimArcLengthSymbol
    {
        zcSymInFront = 0,
        zcSymAbove,
        zcSymNone
    } ZcDimArcLengthSymbol;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(BA2BE7AC-F930-484E-A4BE-C69DAFECC919)] [v1_enum] enum ZcDimHorizontalJustification
    {
        
        zcHorzCentered = 0,
        zcFirstExtensionLine,
        zcSecondExtensionLine,
        zcOverFirstExtension,
        zcOverSecondExtension
    } ZcDimHorizontalJustification;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(ECEFBCE4-98CB-444F-AB2D-95FB5F0CB118)] [v1_enum] enum ZcDimVerticalJustification
    {
        
        zcVertCentered = 0,
        zcAbove,
        zcOutside,
        zcJIS
    } ZcDimVerticalJustification;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(47052D25-4CEB-432C-B8E4-712ACD2CFA06)] [v1_enum] enum ZcDimTextMovement
    {
        
        zcDimLineWithText = 0,
        zcMoveTextAddLeader,
        zcMoveTextNoLeader
    } ZcDimTextMovement;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(71C71889-2E01-4498-B308-66BBCE8AD2B4)] [v1_enum] enum ZcDimToleranceMethod
    {
        
        zcTolNone = 0,
        zcTolSymmetrical,
        zcTolDeviation,
        zcTolLimits,
        zcTolBasic
    } ZcDimToleranceMethod;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(38A96306-7CF8-458F-A7B1-529844E0BDB6)] [v1_enum] enum ZcDimToleranceJustify
    {
        
        zcTolBottom = 0,
        zcTolMiddle,
        zcTolTop
    } ZcDimToleranceJustify;
    
    typedef [helpcontext(IDH_ENUMTYPES), uuid(0C608091-3269-4947-B45B-1F857680222A)] [v1_enum] enum ZcViewportScale
    {
        zcVpScaleToFit = 0,                 
        zcVpCustomScale,                 
        zcVp1,
        zcVp2,
        zcVp3,
        zcVp4,
        zcVp5,
        zcVp6,
        zcVp7,
        zcVp8,
        zcVp9,
        zcVp10,
        zcVp11,
        zcVp12,
        zcVp13,
        zcVp14,
        zcVp15,
        zcVp16,
        zcVp17,
        zcVp18,
        zcVp19,
        zcVp20,
        zcVp21,
        zcVp22,
        zcVp23,
        zcVp24,
        zcVp25,
        zcVp26,
        zcVp27,
        zcVp28,
        zcVp29,
        zcVp30,
        zcVp31,
        zcVp32,
        zcVp33,
        zcVp34,
        zcVp35,
        zcVp36,
        zcVp37,
        zcVp38,
        zcVp39,
        zcVp40,
        zcVp41,
        zcVp42,
        zcVp43,
        zcVp44,
        zcVp45,
        zcVp46,
        zcVp47,
        zcVp48,
        zcVp49,
        zcVp50,
        zcVp51,
        zcVp52,
        zcVp53,
        zcVp54,
        zcVp55,
        zcVp56,
        zcVp57,
        zcVp58,
        zcVp59,
        zcVp60,
        zcVp61,
        zcVp62,
        zcVp63,
        zcVp64,
        zcVp65,
        zcVp66,
        zcVp67,
        zcVp68,
        zcVp69,
        zcVp70,
        zcVp71,
        zcVp72,
        zcVp73,
        zcVp74,
        zcVp75,
        zcVp76,
        zcVp77,
        zcVp78,
        zcVp79,
        zcVp80,
        zcVp81,
        zcVp82,
        zcVp83,
        zcVp84,
        zcVp85,
        zcVp86,
        zcVp87,
        zcVp88,
        zcVp89,
        zcVp90,
        zcVp91,
        zcVp92,
        zcVp93,
        zcVp94,
        zcVp95,
        zcVp96,
        zcVp97,
        zcVp98,
        zcVp99,
        zcVp100,

        zcVp1_1 = zcVpCustomScale +1,
        zcVp1_2,                         
        zcVp1_4,
		zcVp1_5,
        zcVp1_8,                         
        zcVp1_10,                        
        zcVp1_16,                        
        zcVp1_20,                        
        zcVp1_30,                        
        zcVp1_40,                        
        zcVp1_50,                        
        zcVp1_100,                       
        zcVp2_1,                         
        zcVp4_1,                         
        zcVp8_1,                         
        zcVp10_1,                        
        zcVp100_1,                       
        zcVp1_128in_1ft,                 
        zcVp1_64in_1ft,                  
        zcVp1_32in_1ft,                  
        zcVp1_16in_1ft,                  
        zcVp3_32in_1ft,                  
        zcVp1_8in_1ft,                   
        zcVp3_16in_1ft,                  
        zcVp1_4in_1ft,                   
        zcVp3_8in_1ft,                   
        zcVp1_2in_1ft,                   
        zcVp3_4in_1ft,                   
        zcVp1in_1ft,                     
        zcVp1and1_2in_1ft,               
        zcVp3in_1ft,                     
        zcVp6in_1ft,                     
        zcVp1ft_1ft,                     
    } ZcViewportScale;     

    typedef [helpcontext(IDH_ENUMTYPES), uuid(31D0E812-4183-4E71-BF58-A709D6AE4C48)] [v1_enum] enum ZcISOPenWidth
    {
        zcPenWidth013 =  13,
        zcPenWidth018 =  18,
        zcPenWidth025 =  25,
        zcPenWidth035 =  35,
        zcPenWidth050 =  50,
        zcPenWidth070 =  70,
        zcPenWidth100 = 100,
        zcPenWidth140 = 140,
        zcPenWidth200 = 200,
        zcPenWidthUnk =  -1
    } ZcISOPenWidth;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(2EE0E5F6-7114-4C9D-B853-BB1625A6FC71)] [v1_enum] enum ZcSaveAsType
    {
        zcUnknown = -1,
        zcR12_dxf = 1,
        zcR13_dwg = 4,
        zcR13_dxf = 5,
        zcR14_dwg = 8,
        zcR14_dxf = 9,
        zc2000_dwg = 12,
        zc2000_dxf = 13,
        zc2000_Template = 14,
        zc2004_dwg = 24,
        zc2004_dxf = 25,
        zc2004_Template = 26,
        zc2007_dwg = 36,
        zc2007_dxf = 37,
        zc2007_Template = 38,
		zc2010_dwg = 48,
		zc2010_dxf = 49,
		zc2010_Template = 50,
		zc2013_dwg = 60,
		zc2013_dxf = 61,
		zc2013_Template = 62,
        zcNative = zc2013_dwg,

        zcR15_dwg = zc2000_dwg,
        zcR15_dxf = zc2000_dxf,
        zcR15_Template = zc2000_Template,
        zcR18_dwg = zc2004_dwg,
        zcR18_dxf = zc2004_dxf,
        zcR18_Template = zc2004_Template
    } ZcSaveAsType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(B3CEBE27-E22A-4331-B1E6-34E2F9CF304B)] [v1_enum] enum ZcPrinterSpoolAlert
    {
        zcPrinterAlwaysAlert = 0,
        zcPrinterAlertOnce,
        zcPrinterNeverAlertLogOnce,
        zcPrinterNeverAlert
    } ZcPrinterSpoolAlert;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(B47622BA-A94C-4DD0-BE4A-36E799260679)] [v1_enum] enum ZcPlotPolicyForNewDwgs
    {
        zcPolicyNewDefault = 0,
        zcPolicyNewLegacy
    } ZcPlotPolicyForNewDwgs;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(1479CD6D-5FD2-48DD-BF1A-0107A6F2BCA5)] [v1_enum] enum ZcPlotPolicyForLegacyDwgs
    {
        zcPolicyLegacyDefault = 0,
        zcPolicyLegacyQuery,
        zcPolicyLegacyLegacy
    } ZcPlotPolicyForLegacyDwgs;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(DEFC433A-B5D3-4B96-98F3-A439CB6FB9B3)] [v1_enum] enum ZcOleQuality
    {
        zcOQLineArt = 0,
        zcOQText,
        zcOQGraphics,
        zcOQPhoto,
        zcOQHighPhoto
    } ZcOleQuality;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(BD69F6CC-8C5B-4C04-BD38-D5EB8B6F5555)] [v1_enum] enum ZcLoadPalette
    {
        zcPaletteByDrawing = 0,
        zcPaletteBySession
    } ZcLoadPalette;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(9E9163AB-78AD-4A28-AF43-97A8A9BC6F9D)] [v1_enum] enum ZcInsertUnits
    {
        zcInsertUnitsUnitless = 0,
        zcInsertUnitsInches,
        zcInsertUnitsFeet,
        zcInsertUnitsMiles,
        zcInsertUnitsMillimeters,
        zcInsertUnitsCentimeters,
        zcInsertUnitsMeters,
        zcInsertUnitsKilometers,
        zcInsertUnitsMicroinches,
        zcInsertUnitsMils,
        zcInsertUnitsYards,
        zcInsertUnitsAngstroms,
        zcInsertUnitsNanometers,
        zcInsertUnitsMicrons,
        zcInsertUnitsDecimeters,
        zcInsertUnitsDecameters,
        zcInsertUnitsHectometers,
        zcInsertUnitsGigameters,
        zcInsertUnitsAstronomicalUnits,
        zcInsertUnitsLightYears,
        zcInsertUnitsParsecs
    } ZcInsertUnits;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(BD52A8D9-C136-4AC1-9BDC-1F5ECAE98836)] [v1_enum] enum ZcAlignmentPointAcquisition
    {
        zcAlignPntAcquisitionAutomatic = 0,
        zcAlignPntAcquisitionShiftToAcquire
    } ZcAlignmentPointAcquisition;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(85E220F6-A22D-4565-B86A-FA300B95C59C)] [v1_enum] enum ZcInsertUnitsAction
    {
        zcInsertUnitsPrompt = 0,
        zcInsertUnitsAutoAssign
    } ZcInsertUnitsAction;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(A4C847E9-EA9B-447F-BFE5-8A27DFD056A5)] [v1_enum] enum ZcPlotPolicy
    {
        zcPolicyNamed = 0,
        zcPolicyLegacy
    } ZcPlotPolicy;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(589CA7B3-31C1-4947-894C-BEC40DF116E9)] [v1_enum] enum ZcDrawingAreaShortCutMenu
    {
        zcNoDrawingAreaShortCutMenu = 0,
        zcUseDefaultDrawingAreaShortCutMenu
    } ZcDrawingAreaShortCutMenu;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(BBD6F20E-772A-43FF-9387-6275004E13E5)] [v1_enum] enum ZcDrawingAreaSCMDefault
    {
        zcRepeatLastCommand = 0,
        zcSCM
    } ZcDrawingAreaSCMDefault;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(5EFB9B40-CAC3-40DD-9EAE-F9DAD16C251D)] [v1_enum] enum ZcDrawingAreaSCMEdit
    {
        zcEdRepeatLastCommand = 0,
        zcEdSCM
    } ZcDrawingAreaSCMEdit;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(817CF71C-5C11-44EA-9491-5C8F9F081F23)] [v1_enum] enum ZcDrawingAreaSCMCommand
    {
        zcEnter = 0,
        zcEnableSCMOptions,
        zcEnableSCM
    } ZcDrawingAreaSCMCommand;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(776E916E-6B10-4E3C-BF82-B3283B3484B8)] [v1_enum] enum ZcLayerStateMask
    {
        zcLsNone           = 0x0000,
        zcLsOn             = 0x0001,
        zcLsFrozen         = 0x0002,
        zcLsLocked         = 0x0004,
        zcLsPlot           = 0x0008,
        zcLsNewViewport    = 0x0010,
        zcLsColor          = 0x0020,
        zcLsLineType       = 0x0040,
        zcLsLineWeight     = 0x0080,
        zcLsPlotStyle      = 0x0100,
        zcLsAll            = 0xFFFF
    } ZcLayerStateMask;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(C64627AF-1207-4688-8201-D632DB37E9B1)] [v1_enum] enum ZcShadePlot
    {
        zcShadePlotAsDisplayed = 0,
        zcShadePlotWireframe,
        zcShadePlotHidden,
        zcShadePlotRendered
    } ZcShadePlot;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(6A4F6A1C-60D9-44E4-BE9D-7F70E9D96C43)] [v1_enum] enum ZcHatchObjectType
    {
        zcHatchObject = 0,
        zcGradientObject = 1
    } ZcHatchObjectType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(CD4F0280-59DA-4CF9-B4C3-9A8D0D1B54CE)] [v1_enum] enum ZcGradientPatternType
    {
        zcPreDefinedGradient  = 0,
        zcUserDefinedGradient = 1
    } ZcGradientPatternType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(E5265BC5-CC3C-44F3-9D9A-014AF0CBA8C3)] [v1_enum] enum ZcTableDirection
    {
        zcTableTopToBottom  = 0,
        zcTableBottomToTop = 1
    } ZcTableDirection;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(878812BC-D268-41E9-9292-4704BCA8730A)] [v1_enum] enum ZcCellAlignment
    {
        zcTopLeft        = 1,
        zcTopCenter      = 2,
        zcTopRight       = 3,
        zcMiddleLeft     = 4,
        zcMiddleCenter   = 5,
        zcMiddleRight    = 6,
        zcBottomLeft     = 7,
        zcBottomCenter   = 8,
        zcBottomRight    = 9
    } ZcCellAlignment;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(892C199E-736E-4E17-801A-2EEC4826ECA6)] [v1_enum] enum ZcRowType
    {
        zcUnknownRow     = 0,
        zcDataRow        = 1,
        zcTitleRow       = 2,
        zcHeaderRow      = 4
    } ZcRowType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(D6B88E08-5B47-42F5-930A-2D0091C0C2D2)] [v1_enum] enum ZcValueDataType
    {

        zcUnknownDataType   = 0,
        zcLong              = (0x1 << 0),
        zcDouble            = (0x1 << 1),
        zcString            = (0x1 << 2),
        zcDate              = (0x1 << 3),
        zcPoint2d           = (0x1 << 4),
        zcPoint3d           = (0x1 << 5),
        zcObjectId          = (0x1 << 6),
        zcBuffer            = (0x1 << 7),
        zcResbuf            = (0x1 << 8),
        zcGeneral           = (0x1 << 9),

    } ZcValueDataType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(178DC293-7DA5-4DE7-8611-2171524FB7C1)] [v1_enum] enum ZcValueUnitType
    {

        zcUnitless      = 0,
        zcUnitDistance  = (0x1 << 0),
        zcUnitAngle     = (0x1 << 1),
        zcUnitArea      = (0x1 << 2),
        zcUnitVolume    = (0x1 << 3),

    } ZcValueUnitType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(56432ACC-492E-4153-94A3-03B058AAD1E6)] [v1_enum] enum ZcParseOption
    {

        zcParseOptionNone       = 0,
        zcSetDefaultFormat      = (0x1 << 0),
        zcPreserveMtextFormat   = (0x1 << 1),

    } ZcParseOption;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(AB0BD41B-8FF3-4ED0-AA9A-6035230FCFF0)] [v1_enum] enum ZcFormatOption
    {

        kFormatOptionNone       = 0,
        zcForEditing            = (0x1 << 0),
        zcForExpression         = (0x1 << 1),
        zcUseMaximumPrecision   = (0x1 << 2),
        zcIgnoreMtextFormat     = (0x1 << 3),

    } ZcFormatOption;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(9CE36164-EA49-4C1E-A89A-DC6D09E9EA04)] [v1_enum] enum ZcGridLineType
    {
        zcInvalidGridLine = 0,
        zcHorzTop        = 1,
        zcHorzInside     = 2,
        zcHorzBottom     = 4,
        zcVertLeft       = 8,
        zcVertInside     = 0x10,
        zcVertRight      = 0x20 

    } ZcGridLineType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(E397177C-369B-4C7B-ABD0-20F948D8BAB0)] [v1_enum] enum ZcCellType
    {
        zcUnknownCell = 0,
        zcTextCell= 1,
        zcBlockCell= 2,

    } ZcCellType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(6F9E2AC2-2F95-4843-BF7A-415AA39EE3B0)] [v1_enum] enum ZcCellEdgeMask
    {
        zcTopMask= 1,
        zcRightMask= 2,
        zcBottomMask= 4,
        zcLeftMask= 8,

    } ZcCellEdgeMask;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(194F0739-222D-4E19-AE6F-A6080F3B9A30)] [v1_enum] enum ZcRotationAngle
    {
        zcDegreesUnknown = -1,
        zcDegrees000     = 0,
        zcDegrees090     = 1,
        zcDegrees180     = 2,
        zcDegrees270     = 3,

    } ZcRotationAngle;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(87BA736B-8D4F-45D4-B373-3B09DC8772ED)] [v1_enum] enum ZcMergeCellStyleOption
    {
        zcMergeCellStyleNone                         = 0,
        zcMergeCellStyleCopyDuplicates               = 0x1,
        zcMergeCellStyleOverwriteDuplicates          = 0x2,
        zcMergeCellStyleConvertDuplicatesToOverrides = 0x4,
        zcMergeCellStyleIgnoreNewStyles              = 0x8,

    } ZcMergeCellStyleOption;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(CE1E5544-A34B-4299-AC3C-61EF736FE02C)] [v1_enum] enum ZcSelectType
    {
        zcTableSelectWindow= 1,
        zcTableSelectCrossing= 2,

    } ZcSelectType;

	typedef [helpcontext(IDH_ENUMTYPES), uuid(B28242F7-3EE3-4B47-A89F-4A31556F78C6)] [v1_enum] enum ZcOleType
    {
		zcOTLink = 1,
		zcOTEmbedded = 2,
		zcOTStatic = 3
	} ZcOleType;

	typedef [helpcontext(IDH_ENUMTYPES), uuid(5F829DCC-8BE1-4BE4-8483-918923F6D232)] [v1_enum] enum ZcOlePlotQuality
    {
        zcOPQMonochrome = 0,
        zcOPQLowGraphics,
        zcOPQHighGraphics
    } ZcOlePlotQuality;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(7D4B4DE7-51FE-4001-BDF0-92E9BF00CCFA)] [v1_enum] enum ZcTableStyleOverrides
    {
        
        zcTitleSuppressed             = 1,
        zcHeaderSuppressed            = 2,
        zcFlowDirection               = 3,
        zcHorzCellMargin              = 4,
        zcVertCellMargin              = 5,
        zcTitleRowColor               = 6,
        zcHeaderRowColor              = 7,
        zcDataRowColor                = 8,
        zcTitleRowFillNone            = 9,
        zcHeaderRowFillNone           = 10,
        zcDataRowFillNone             = 11,
        zcTitleRowFillColor           = 12,
        zcHeaderRowFillColor          = 13,
        zcDataRowFillColor            = 14,
        zcTitleRowAlignment           = 15,
        zcHeaderRowAlignment          = 16,
        zcDataRowAlignment            = 17,
        zcTitleRowTextStyle           = 18,
        zcHeaderRowTextStyle          = 19,
        zcDataRowTextStyle            = 20,
        zcTitleRowTextHeight          = 21,
        zcHeaderRowTextHeight         = 22,
        zcDataRowTextHeight           = 23,
        zcTitleRowDataType            = 24,
        zcHeaderRowDataType           = 25,
        zcDataRowDataType             = 26,

        zcTitleHorzTopColor           = 40,
        zcTitleHorzInsideColor        = 41,
        zcTitleHorzBottomColor        = 42,
        zcTitleVertLeftColor          = 43,
        zcTitleVertInsideColor        = 44,
        zcTitleVertRightColor         = 45,
        zcHeaderHorzTopColor          = 46,
        zcHeaderHorzInsideColor       = 47,
        zcHeaderHorzBottomColor       = 48,
        zcHeaderVertLeftColor         = 49,
        zcHeaderVertInsideColor       = 50,
        zcHeaderVertRightColor        = 51,
        zcDataHorzTopColor            = 52,
        zcDataHorzInsideColor         = 53,
        zcDataHorzBottomColor         = 54,
        zcDataVertLeftColor           = 55,
        zcDataVertInsideColor         = 56,
        zcDataVertRightColor          = 57,

        zcTitleHorzTopLineWeight      = 70,
        zcTitleHorzInsideLineWeight   = 71,
        zcTitleHorzBottomLineWeight   = 72,
        zcTitleVertLeftLineWeight     = 73,
        zcTitleVertInsideLineWeight   = 74,
        zcTitleVertRightLineWeight    = 75,
        zcHeaderHorzTopLineWeight     = 76,
        zcHeaderHorzInsideLineWeight  = 77,
        zcHeaderHorzBottomLineWeight  = 78,
        zcHeaderVertLeftLineWeight    = 79,
        zcHeaderVertInsideLineWeight  = 80,
        zcHeaderVertRightLineWeight   = 81,
        zcDataHorzTopLineWeight       = 82,
        zcDataHorzInsideLineWeight    = 83,
        zcDataHorzBottomLineWeight    = 84,
        zcDataVertLeftLineWeight      = 85,
        zcDataVertInsideLineWeight    = 86,
        zcDataVertRightLineWeight     = 87,

        zcTitleHorzTopVisibility      = 100,
        zcTitleHorzInsideVisibility   = 101,
        zcTitleHorzBottomVisibility   = 102,
        zcTitleVertLeftVisibility     = 103,
        zcTitleVertInsideVisibility   = 104,
        zcTitleVertRightVisibility    = 105,
        zcHeaderHorzTopVisibility     = 106,
        zcHeaderHorzInsideVisibility  = 107,
        zcHeaderHorzBottomVisibility  = 108,
        zcHeaderVertLeftVisibility    = 109,
        zcHeaderVertInsideVisibility  = 110,
        zcHeaderVertRightVisibility   = 111,
        zcDataHorzTopVisibility       = 112,
        zcDataHorzInsideVisibility    = 113,
        zcDataHorzBottomVisibility    = 114,
        zcDataVertLeftVisibility      = 115,
        zcDataVertInsideVisibility    = 116,
        zcDataVertRightVisibility     = 117,

        zcCellAlign                   = 130,
        zcCellBackgroundFillNone      = 131,
        zcCellBackgroundColor         = 132,
        zcCellContentColor            = 133,
        zcCellTextStyle               = 134,
        zcCellTextHeight              = 135,
        zcCellTopGridColor            = 136,
        zcCellRightGridColor          = 137,
        zcCellBottomGridColor         = 138,
        zcCellLeftGridColor           = 139,
        zcCellTopGridLineWeight       = 140,
        zcCellRightGridLineWeight     = 141,
        zcCellBottomGridLineWeight    = 142,
        zcCellLeftGridLineWeight      = 143,
        zcCellTopVisibility           = 144,
        zcCellRightVisibility         = 145,
        zcCellBottomVisibility        = 146,
        zcCellLeftVisibility          = 147,
        zcCellDataType                = 148,

    } ZcTableStyleOverrides;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(35C3A80D-ED5F-43A0-B111-ED02D91798FE)] [v1_enum] enum ZcMLineJustification
    {
        zcTop        = 0,
        zcZero       = 1,
        zcBottom     = 2
    } ZcMLineJustification;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(028F7EBD-5131-47C7-9974-AADABF15FD45)] [v1_enum] enum ZcBlockScaling
    {
        zcAny       = 0,
        zcUniform   = 1
    } ZcBlockScaling;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(BF9EFD16-E543-49A5-882C-872ACCA24536)] [v1_enum] enum ZcDynamicBlockReferencePropertyUnitsType
    {
            zcNoUnits  = 0,
            zcAngular  = 1,
            zcDistance = 2,
            zcArea     = 3
    } ZcDynamicBlockReferencePropertyUnitsType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(2FA654AE-4194-4E29-BB91-6196669C8191)] [v1_enum] enum ZcSectionState
    {

        zcSectionStatePlane     = (0x1 << 0),
        zcSectionStateBoundary  = (0x1 << 1),
        zcSectionStateVolume    = (0x1 << 2),

    } ZcSectionState;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(EBEF2582-191E-422D-AA50-E62B625EC3FE)] [v1_enum] enum ZcSectionSubItem
    {

        zcSectionSubItemkNone              = 0,
        zcSectionSubItemSectionLine        = (0x1 << 0),
        zcSectionSubItemSectionLineTop     = (0x1 << 1),
        zcSectionSubItemSectionLineBottom  = (0x1 << 2),
        zcSectionSubItemBackLine           = (0x1 << 3),
        zcSectionSubItemBackLineTop        = (0x1 << 4),
        zcSectionSubItemBackLineBottom     = (0x1 << 5),
        zcSectionSubItemVerticalLineTop    = (0x1 << 6),
        zcSectionSubItemVerticalLineBottom = (0x1 << 7),

    } ZcSectionSubItem;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(4CA641A9-24ED-4469-B27D-0BD287B8CE63)] [v1_enum] enum ZcSectionType
    {

        zcSectionTypeLiveSection   = (0x1 << 0),
        zcSectionType2dSection     = (0x1 << 1),
        zcSectionType3dSection     = (0x1 << 2),

    } ZcSectionType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(7EE9D2DD-AD10-4F15-A811-ECC9E6F997D7)] [v1_enum] enum ZcSectionGeneration
    {

        zcSectionGenerationSourceAllObjects          = (0x1 << 0),
        zcSectionGenerationSourceSelectedObjects     = (0x1 << 1),
        zcSectionGenerationDestinationNewBlock       = (0x1 << 4),
        zcSectionGenerationDestinationReplaceBlock   = (0x1 << 5),
        zcSectionGenerationDestinationFile           = (0x1 << 6),

    } ZcSectionGeneration;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(E51414C8-EBF3-4513-A6C9-07AB39813607)] [v1_enum] enum ZcHelixConstrainType
    {
        zcTurnHeight  = 0,
        zcTurns       = 1,
        zcHeight      = 2

    } ZcHelixConstrainType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(B77CC5C9-95B3-4874-9F49-18CEB3899777)] [v1_enum] enum ZcShadowDisplayType
    {
        zcCastsAndReceivesShadows = 0,
        zcCastsShadows = 1,
        zcReceivesShadows = 2,
        zcIgnoreShadows = 3
    } ZcShadowDisplayType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(81E87D9A-064C-4DC3-8892-9BF4B0E6CE83)] [v1_enum] enum ZcLoftedSurfaceNormalType
    {
        zcRuled = 0,
        zcSmooth = 1,
        zcFirstNormal = 2,
        zcLastNormal = 3,
        zcEndsNormal = 4,
        zcAllNormal = 5,
        zcUseDraftAngles = 6
    } ZcLoftedSurfaceNormalType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(D89F3DDB-B1ED-4383-B76E-31CFBA9AB495)] [v1_enum] enum ZcHelixTwistType
    {
        zcCCW = 0,
        zcCW = 1
    } ZcHelixTwistType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(3D4C30A9-9B87-414C-98BB-6181C84C7803)] [v1_enum] enum ZcUnderlayLayerOverrideType
    {
        zcNoOverrides = 0,
        zcApplied = 1
    } ZcUnderlayLayerOverrideType;

    typedef [uuid(791DF8B6-D2B0-477A-AA04-F2310EFAF877)] [v1_enum] enum ZcTableFlowDirection
    {
        zcTableFlowRight     = 0x1,
        zcTableFlowDownOrUp = 0x2,
        zcTableFlowLeft= 0x4,
    } ZcTableFlowDirection;

    typedef [uuid(13CCA8A2-F385-4677-ABD9-4B07E34AC11E)] [v1_enum] enum ZcCellMargin
    {
        zcCellMarginTop     = 0x1,
        zcCellMarginLeft    = 0x2,
        zcCellMarginBottom  = 0x4,
        zcCellMarginRight   = 0x8,
        zcCellMarginHorzSpacing = 0x10,
        zcCellMarginVertSpacing = 0x20,
    } ZcCellMargin;

    typedef [uuid(39622BF4-035C-43A5-99FE-75EF92194BAB)] [v1_enum] enum ZcCellContentLayout
    {
        zcCellContentLayoutFlow              = 0x1,
        zcCellContentLayoutStackedHorizontal = 0x2,
        zcCellContentLayoutStackedVertical   = 0x4,
    } ZcCellContentLayout;

    typedef [uuid(569724BA-FF07-44EF-A55C-3665566279CC)] [v1_enum] enum ZcCellProperty
    {

           zcInvalidCellProperty     = 0,
           zcLock                    = (0x1 << 0),
           zcDataType                = (0x1 << 1),
           zcDataFormat              = (0x1 << 2),
           zcRotation                = (0x1 << 3),
           zcScale                   = (0x1 << 4),
           zcAlignmentProperty       = (0x1 << 5),
           zcContentColor            = (0x1 << 6),
           zcBackgroundColor         = (0x1 << 7),
           zcTextStyle               = (0x1 << 8),
           zcTextHeight              = (0x1 << 9),
           zcMarginLeft              = (0x1 << 10),
           zcMarginTop               = (0x1 << 11),
           zcMarginRight             = (0x1 << 12),
           zcMarginBottom            = (0x1 << 13),
           zcEnableBackgroundColor   = (0x1 << 14),
           zcAutoScale               = (0x1 << 15),
           zcMergeAll                = (0x1 << 16),
           zcFlowDirBtoT             = (0x1 << 17),
           zcContentLayout           = (0x1 << 18),
           zcDataTypeAndFormat       = (zcDataType | zcDataFormat),
           zcContentProperties       = (zcDataType | zcDataFormat | zcRotation |
                                       zcScale | zcAlignmentProperty | zcContentColor |
                                       zcTextStyle | zcTextHeight | zcAutoScale),

           zcBitProperties           = (zcEnableBackgroundColor | zcAutoScale | zcMergeAll | zcFlowDirBtoT),

           zcAllCellProperties       = (zcLock | zcDataType | zcDataFormat | zcRotation |
                                       zcScale | zcAlignmentProperty | zcContentColor | zcBackgroundColor |
                                       zcTextStyle | zcTextHeight | zcMarginLeft | zcMarginTop |
                                       zcMarginRight | zcMarginBottom | zcEnableBackgroundColor |
                                       zcAutoScale | zcMergeAll | zcFlowDirBtoT | zcContentLayout),

    } ZcCellProperty;

    typedef [uuid(F8D9F752-3992-4619-B116-9A8E9A2E319D)] [v1_enum] enum ZcGridLineStyle
    {
        zcGridLineStyleSingle = 1,
        zcGridLineStyleDouble = 2,
    } ZcGridLineStyle;

    typedef [uuid(FC3EAA2A-26DC-4720-8710-941D361D7390)] [v1_enum] enum ZcDataLinkUpdateDirection
    {
        zcUpdateDataFromSource   = 0x1,
        zcUpdateSourceFromData   = 0x2,
    } ZcDataLinkUpdateDirection;

    typedef [uuid(1568B6E2-852D-4B40-9A9D-9324BBA2EA8E)] [v1_enum] enum ZcDataLinkUpdateOption
    {
        zcUpdateOptionNone                                  = 0,
        zcUpdateOptionOverwriteContentModifiedAfterUpdate   = 0x20000,
        zcUpdateOptionOverwriteFormatModifiedAfterUpdate    = 0x40000,
        zcUpdateOptionUpdateFullSourceRange                 = 0x80000,
        zcUpdateOptionIncludeXrefs                          = 0x100000,
    } ZcDataLinkUpdateOption;

    typedef [uuid(32C4685D-F1BB-4B6D-94E6-6C6C37A0B9BD)] [v1_enum] enum ZcCellContentType
    {
        zcCellContentTypeUnknown = 0,
        zcCellContentTypeValue   = (0x1 << 0),
        zcCellContentTypeField   = (0x1 << 1),
        zcCellContentTypeBlock   = (0x1 << 2),
    } ZcCellContentType;

    typedef [uuid(A489E282-9AA0-4E20-9ED6-1318D8538AC4)][v1_enum] enum ZcCellState
    {
        zcCellStateNone             = 0,
        zcCellStateContentLocked    = 0x1,
        zcCellStateContentReadOnly  = 0x2,
        zcCellStateFormatLocked     = 0x4,
        zcCellStateFormatReadOnly   = 0x8,
        zcCellStateLinked           = 0x10,
        zcCellStateContentModified  = 0x20,
        zcCellStateFormatModified   = 0x40,
    } ZcCellState;

    typedef [uuid(D4B371BF-206B-4BCE-8C01-FAC28E6E93B3)][v1_enum] enum ZcCellOption
    {
        kCellOptionNone    = 0,
        kInheritCellFormat = 0x1,
    } ZcCellOption;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(7F39125C-0ACC-48C9-A6A6-A8E6F015FFDE)] [v1_enum] enum ZcTextAttachmentType
    {
        zcAttachmentTopOfTop        = 0,
        zcAttachmentMiddleOfTop     = 1,
        zcAttachmentBottomOfTop     = 2,
        zcAttachmentBottomOfTopLine = 3,
        zcAttachmentMiddle          = 4,
        zcAttachmentMiddleOfBottom  = 5,
        zcAttachmentBottomOfBottom  = 6,
        zcAttachmentBottomLine      = 7,
        zcAttachmentAllLine         = 8
    } ZcTextAttachmentType;

	typedef [helpcontext(IDH_ENUMTYPES), uuid(9310D252-E501-4400-856E-8E66655F5ECD)] [v1_enum] enum ZcTextAttachmentDirection
	{
        zcAttachmentHorizontal = 0,
        zcAttachmentVertical = 1
    } ZcTextAttachmentDirection;

	typedef [helpcontext(IDH_ENUMTYPES), uuid(D231B785-62D7-4A4F-85C2-7010F65F8440)] [v1_enum] enum ZcVerticalTextAttachmentType
	{
        zcAttachmentCenter = 0,
        zcAttachmentLinedCenter = 1
    } ZcVerticalTextAttachmentType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(7437B0FA-6D22-4732-9C14-DE47BA9E0B68)] [v1_enum] enum ZcMLeaderType
    {
        zcStraightLeader            = 1,
        zcSplineLeader              = 2,
        zcInVisibleLeader           = 0
    } ZcMLeaderType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(AD938B21-1CF2-453A-B6FB-E3D24D3FEF9E)] [v1_enum] enum ZcMLeaderContentType
    {
        zcNoneContent                = 0,
        zcBlockContent               = 1,
        zcMTextContent               = 2
    } ZcMLeaderContentType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(094CB4D6-D747-4BEF-BB5F-A71E06605518)] [v1_enum] enum ZcTextAlignmentType
    {
        zcLeftAlignment             = 0,
        zcCenterAlignment           = 1,
        zcRightAlignment            = 2
    } ZcTextAlignmentType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(5E99EB64-848C-49D0-AC68-19327A5B28AD)] [v1_enum] enum ZcTextAngleType
    {
        zcInsertAngle               = 0,
        zcHorizontalAngle           = 1,
        zcAlwaysRightReadingAngle   = 2
    } ZcTextAngleType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(A43C9F8F-6478-47E3-A3E2-A8B4CF62A93C)] [v1_enum] enum ZcBlockConnectionType {
        zcConnectExtents            = 0,
        zcConnectBase               = 1
    } ZcBlockConnectionType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(29F96187-ABA8-464D-9067-9429B584C209)] [v1_enum] enum ZcPredefBlockType
    {
        zcBlockImperial      =  0,
        zcBlockSlot          =  1,
        zcBlockCircle        =  2,
        zcBlockBox           =  3,
        zcBlockHexagon       =  4,
        zcBlockTriangle      =  5,
        zcBlockUserDefined   =  6
    } ZcPredefBlockType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(4FEB553B-8F65-4A95-8D49-4E1C836D18B7)] [v1_enum] enum ZcDrawLeaderOrderType {
        zcDrawLeaderHeadFirst            = 0,
        zcDrawLeaderTailFirst            = 1
    } ZcDrawLeaderOrderType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(460AA264-D8F2-4753-98AF-1B6F63CCC006)] [v1_enum] enum ZcDrawMLeaderOrderType {
        zcDrawContentFirst            = 0,
        zcDrawLeaderFirst            = 1
    } ZcDrawMLeaderOrderType;

    typedef [helpcontext(IDH_ENUMTYPES), uuid(3E40CB90-3F09-479E-B0CD-719E6528B44A)] [v1_enum] enum ZcSegmentAngleType {
        zcDegreesAny            = 0,
        zcDegrees15            = 1,
        zcDegrees30            = 2,
        zcDegrees45            = 3,
        zcDegrees60            = 4,
        zcDegrees90            = 6,
        zcDegreesHorz            = 12
    } ZcSegmentAngleType;
