
#ifndef __ACPP_H__
#define __ACPP_H__

#include "../inc/zacpp.h"

#ifndef ACPPINPUT_ID_BASEPOINT
#define ACPPINPUT_ID_BASEPOINT		ZCPPINPUT_ID_BASEPOINT
#endif //#ifndef ACPPINPUT_ID_BASEPOINT

#ifndef ACPPINPUT_ID_CRONLY
#define ACPPINPUT_ID_CRONLY		ZCPPINPUT_ID_CRONLY
#endif //#ifndef ACPPINPUT_ID_CRONLY

#ifndef ACPPINPUT_ID_DOCUMENT
#define ACPPINPUT_ID_DOCUMENT		ZCPPINPUT_ID_DOCUMENT
#endif //#ifndef ACPPINPUT_ID_DOCUMENT

#ifndef ACPPINPUT_ID_ENABLENOTIFICATION
#define ACPPINPUT_ID_ENABLENOTIFICATION		ZCPPINPUT_ID_ENABLENOTIFICATION
#endif //#ifndef ACPPINPUT_ID_ENABLENOTIFICATION

#ifndef ACPPINPUT_ID_INITGETBIT
#define ACPPINPUT_ID_INITGETBIT		ZCPPINPUT_ID_INITGETBIT
#endif //#ifndef ACPPINPUT_ID_INITGETBIT

#ifndef ACPPINPUT_ID_INITGETKWORD
#define ACPPINPUT_ID_INITGETKWORD		ZCPPINPUT_ID_INITGETKWORD
#endif //#ifndef ACPPINPUT_ID_INITGETKWORD

#ifndef ACPPINPUT_ID_PROMPT
#define ACPPINPUT_ID_PROMPT		ZCPPINPUT_ID_PROMPT
#endif //#ifndef ACPPINPUT_ID_PROMPT

#ifndef ACPPINPUT_ID_PROMPT2
#define ACPPINPUT_ID_PROMPT2		ZCPPINPUT_ID_PROMPT2
#endif //#ifndef ACPPINPUT_ID_PROMPT2

#ifndef ACPPINPUT_ID_PROMPTTYPE
#define ACPPINPUT_ID_PROMPTTYPE		ZCPPINPUT_ID_PROMPTTYPE
#endif //#ifndef ACPPINPUT_ID_PROMPTTYPE

#ifndef ACPPINPUT_ID_STATUS
#define ACPPINPUT_ID_STATUS		ZCPPINPUT_ID_STATUS
#endif //#ifndef ACPPINPUT_ID_STATUS

#ifndef ACPPINPUT_ID_VALUE
#define ACPPINPUT_ID_VALUE		ZCPPINPUT_ID_VALUE
#endif //#ifndef ACPPINPUT_ID_VALUE

#ifndef AcPpAcadInput
#define AcPpAcadInput		ZcPpZcadInput
#endif //#ifndef AcPpAcadInput

#ifndef AcPpNavTree
#define AcPpNavTree		ZcPpNavTree
#endif //#ifndef AcPpNavTree

#ifndef AcPpNavTreeNode
#define AcPpNavTreeNode		ZcPpNavTreeNode
#endif //#ifndef AcPpNavTreeNode

#ifndef AcPpPalette
#define AcPpPalette		ZcPpPalette
#endif //#ifndef AcPpPalette

#ifndef AcPpPalette2
#define AcPpPalette2		ZcPpPalette2
#endif //#ifndef AcPpPalette2

#ifndef AcPpPaletteSet
#define AcPpPaletteSet		ZcPpPaletteSet
#endif //#ifndef AcPpPaletteSet

#ifndef CLSID_AcPp
#define CLSID_AcPp		CLSID_ZcPp
#endif //#ifndef CLSID_AcPp

#ifndef CLSID_AcPpAcadInput
#define CLSID_AcPpAcadInput		CLSID_ZcPpZcadInput
#endif //#ifndef CLSID_AcPpAcadInput

#ifndef CLSID_AcPpNavTree
#define CLSID_AcPpNavTree		CLSID_ZcPpNavTree
#endif //#ifndef CLSID_AcPpNavTree

#ifndef CLSID_AcPpNavTreeNode
#define CLSID_AcPpNavTreeNode		CLSID_ZcPpNavTreeNode
#endif //#ifndef CLSID_AcPpNavTreeNode

#ifndef CLSID_AcPpPalette
#define CLSID_AcPpPalette		CLSID_ZcPpPalette
#endif //#ifndef CLSID_AcPpPalette

#ifndef CLSID_AcPpPalette2
#define CLSID_AcPpPalette2		CLSID_ZcPpPalette2
#endif //#ifndef CLSID_AcPpPalette2

#ifndef CLSID_AcPpPaletteSet
#define CLSID_AcPpPaletteSet		CLSID_ZcPpPaletteSet
#endif //#ifndef CLSID_AcPpPaletteSet

#ifndef CLSID_AcPpZcadInput
#define CLSID_AcPpZcadInput		CLSID_ZcPpZcadInput
#endif //#ifndef CLSID_AcPpZcadInput

#ifndef IAcPiPropertyInspector
#define IAcPiPropertyInspector		IZcPiPropertyInspector
#endif //#ifndef IAcPiPropertyInspector

#ifndef IAcPp
#define IAcPp		IZcPp
#endif //#ifndef IAcPp

#ifndef IAcPpAcadInput
#define IAcPpAcadInput		IZcPpZcadInput
#endif //#ifndef IAcPpAcadInput

#ifndef IAcPpAcadInputVtbl
#define IAcPpAcadInputVtbl		IZcPpZcadInputVtbl
#endif //#ifndef IAcPpAcadInputVtbl

#ifndef IAcPpAcadInput_AddRef
#define IAcPpAcadInput_AddRef		IZcPpZcadInput_AddRef
#endif //#ifndef IAcPpAcadInput_AddRef

#ifndef IAcPpAcadInput_CancelPrompt
#define IAcPpAcadInput_CancelPrompt		IZcPpZcadInput_CancelPrompt
#endif //#ifndef IAcPpAcadInput_CancelPrompt

#ifndef IAcPpAcadInput_CancelPrompt_Proxy
#define IAcPpAcadInput_CancelPrompt_Proxy		IZcPpZcadInput_CancelPrompt_Proxy
#endif //#ifndef IAcPpAcadInput_CancelPrompt_Proxy

#ifndef IAcPpAcadInput_CancelPrompt_Stub
#define IAcPpAcadInput_CancelPrompt_Stub		IZcPpZcadInput_CancelPrompt_Stub
#endif //#ifndef IAcPpAcadInput_CancelPrompt_Stub

#ifndef IAcPpAcadInput_DoPrompt
#define IAcPpAcadInput_DoPrompt		IZcPpZcadInput_DoPrompt
#endif //#ifndef IAcPpAcadInput_DoPrompt

#ifndef IAcPpAcadInput_DoPrompt_Proxy
#define IAcPpAcadInput_DoPrompt_Proxy		IZcPpZcadInput_DoPrompt_Proxy
#endif //#ifndef IAcPpAcadInput_DoPrompt_Proxy

#ifndef IAcPpAcadInput_DoPrompt_Stub
#define IAcPpAcadInput_DoPrompt_Stub		IZcPpZcadInput_DoPrompt_Stub
#endif //#ifndef IAcPpAcadInput_DoPrompt_Stub

#ifndef IAcPpAcadInput_QueryInterface
#define IAcPpAcadInput_QueryInterface		IZcPpZcadInput_QueryInterface
#endif //#ifndef IAcPpAcadInput_QueryInterface

#ifndef IAcPpAcadInput_Release
#define IAcPpAcadInput_Release		IZcPpZcadInput_Release
#endif //#ifndef IAcPpAcadInput_Release

#ifndef IAcPpAcadInput_get_BasePoint
#define IAcPpAcadInput_get_BasePoint		IZcPpZcadInput_get_BasePoint
#endif //#ifndef IAcPpAcadInput_get_BasePoint

#ifndef IAcPpAcadInput_get_BasePoint_Proxy
#define IAcPpAcadInput_get_BasePoint_Proxy		IZcPpZcadInput_get_BasePoint_Proxy
#endif //#ifndef IAcPpAcadInput_get_BasePoint_Proxy

#ifndef IAcPpAcadInput_get_BasePoint_Stub
#define IAcPpAcadInput_get_BasePoint_Stub		IZcPpZcadInput_get_BasePoint_Stub
#endif //#ifndef IAcPpAcadInput_get_BasePoint_Stub

#ifndef IAcPpAcadInput_get_CrOnly
#define IAcPpAcadInput_get_CrOnly		IZcPpZcadInput_get_CrOnly
#endif //#ifndef IAcPpAcadInput_get_CrOnly

#ifndef IAcPpAcadInput_get_CrOnly_Proxy
#define IAcPpAcadInput_get_CrOnly_Proxy		IZcPpZcadInput_get_CrOnly_Proxy
#endif //#ifndef IAcPpAcadInput_get_CrOnly_Proxy

#ifndef IAcPpAcadInput_get_CrOnly_Stub
#define IAcPpAcadInput_get_CrOnly_Stub		IZcPpZcadInput_get_CrOnly_Stub
#endif //#ifndef IAcPpAcadInput_get_CrOnly_Stub

#ifndef IAcPpAcadInput_get_Document
#define IAcPpAcadInput_get_Document		IZcPpZcadInput_get_Document
#endif //#ifndef IAcPpAcadInput_get_Document

#ifndef IAcPpAcadInput_get_Document_Proxy
#define IAcPpAcadInput_get_Document_Proxy		IZcPpZcadInput_get_Document_Proxy
#endif //#ifndef IAcPpAcadInput_get_Document_Proxy

#ifndef IAcPpAcadInput_get_Document_Stub
#define IAcPpAcadInput_get_Document_Stub		IZcPpZcadInput_get_Document_Stub
#endif //#ifndef IAcPpAcadInput_get_Document_Stub

#ifndef IAcPpAcadInput_get_EnableNotification
#define IAcPpAcadInput_get_EnableNotification		IZcPpZcadInput_get_EnableNotification
#endif //#ifndef IAcPpAcadInput_get_EnableNotification

#ifndef IAcPpAcadInput_get_EnableNotification_Proxy
#define IAcPpAcadInput_get_EnableNotification_Proxy		IZcPpZcadInput_get_EnableNotification_Proxy
#endif //#ifndef IAcPpAcadInput_get_EnableNotification_Proxy

#ifndef IAcPpAcadInput_get_EnableNotification_Stub
#define IAcPpAcadInput_get_EnableNotification_Stub		IZcPpZcadInput_get_EnableNotification_Stub
#endif //#ifndef IAcPpAcadInput_get_EnableNotification_Stub

#ifndef IAcPpAcadInput_get_InitGetBit
#define IAcPpAcadInput_get_InitGetBit		IZcPpZcadInput_get_InitGetBit
#endif //#ifndef IAcPpAcadInput_get_InitGetBit

#ifndef IAcPpAcadInput_get_InitGetBit_Proxy
#define IAcPpAcadInput_get_InitGetBit_Proxy		IZcPpZcadInput_get_InitGetBit_Proxy
#endif //#ifndef IAcPpAcadInput_get_InitGetBit_Proxy

#ifndef IAcPpAcadInput_get_InitGetBit_Stub
#define IAcPpAcadInput_get_InitGetBit_Stub		IZcPpZcadInput_get_InitGetBit_Stub
#endif //#ifndef IAcPpAcadInput_get_InitGetBit_Stub

#ifndef IAcPpAcadInput_get_InitGetKword
#define IAcPpAcadInput_get_InitGetKword		IZcPpZcadInput_get_InitGetKword
#endif //#ifndef IAcPpAcadInput_get_InitGetKword

#ifndef IAcPpAcadInput_get_InitGetKword_Proxy
#define IAcPpAcadInput_get_InitGetKword_Proxy		IZcPpZcadInput_get_InitGetKword_Proxy
#endif //#ifndef IAcPpAcadInput_get_InitGetKword_Proxy

#ifndef IAcPpAcadInput_get_InitGetKword_Stub
#define IAcPpAcadInput_get_InitGetKword_Stub		IZcPpZcadInput_get_InitGetKword_Stub
#endif //#ifndef IAcPpAcadInput_get_InitGetKword_Stub

#ifndef IAcPpAcadInput_get_Prompt
#define IAcPpAcadInput_get_Prompt		IZcPpZcadInput_get_Prompt
#endif //#ifndef IAcPpAcadInput_get_Prompt

#ifndef IAcPpAcadInput_get_Prompt2
#define IAcPpAcadInput_get_Prompt2		IZcPpZcadInput_get_Prompt2
#endif //#ifndef IAcPpAcadInput_get_Prompt2

#ifndef IAcPpAcadInput_get_Prompt2_Proxy
#define IAcPpAcadInput_get_Prompt2_Proxy		IZcPpZcadInput_get_Prompt2_Proxy
#endif //#ifndef IAcPpAcadInput_get_Prompt2_Proxy

#ifndef IAcPpAcadInput_get_Prompt2_Stub
#define IAcPpAcadInput_get_Prompt2_Stub		IZcPpZcadInput_get_Prompt2_Stub
#endif //#ifndef IAcPpAcadInput_get_Prompt2_Stub

#ifndef IAcPpAcadInput_get_PromptType
#define IAcPpAcadInput_get_PromptType		IZcPpZcadInput_get_PromptType
#endif //#ifndef IAcPpAcadInput_get_PromptType

#ifndef IAcPpAcadInput_get_PromptType_Proxy
#define IAcPpAcadInput_get_PromptType_Proxy		IZcPpZcadInput_get_PromptType_Proxy
#endif //#ifndef IAcPpAcadInput_get_PromptType_Proxy

#ifndef IAcPpAcadInput_get_PromptType_Stub
#define IAcPpAcadInput_get_PromptType_Stub		IZcPpZcadInput_get_PromptType_Stub
#endif //#ifndef IAcPpAcadInput_get_PromptType_Stub

#ifndef IAcPpAcadInput_get_Prompt_Proxy
#define IAcPpAcadInput_get_Prompt_Proxy		IZcPpZcadInput_get_Prompt_Proxy
#endif //#ifndef IAcPpAcadInput_get_Prompt_Proxy

#ifndef IAcPpAcadInput_get_Prompt_Stub
#define IAcPpAcadInput_get_Prompt_Stub		IZcPpZcadInput_get_Prompt_Stub
#endif //#ifndef IAcPpAcadInput_get_Prompt_Stub

#ifndef IAcPpAcadInput_get_Status
#define IAcPpAcadInput_get_Status		IZcPpZcadInput_get_Status
#endif //#ifndef IAcPpAcadInput_get_Status

#ifndef IAcPpAcadInput_get_Status_Proxy
#define IAcPpAcadInput_get_Status_Proxy		IZcPpZcadInput_get_Status_Proxy
#endif //#ifndef IAcPpAcadInput_get_Status_Proxy

#ifndef IAcPpAcadInput_get_Status_Stub
#define IAcPpAcadInput_get_Status_Stub		IZcPpZcadInput_get_Status_Stub
#endif //#ifndef IAcPpAcadInput_get_Status_Stub

#ifndef IAcPpAcadInput_get_Value
#define IAcPpAcadInput_get_Value		IZcPpZcadInput_get_Value
#endif //#ifndef IAcPpAcadInput_get_Value

#ifndef IAcPpAcadInput_get_Value_Proxy
#define IAcPpAcadInput_get_Value_Proxy		IZcPpZcadInput_get_Value_Proxy
#endif //#ifndef IAcPpAcadInput_get_Value_Proxy

#ifndef IAcPpAcadInput_get_Value_Stub
#define IAcPpAcadInput_get_Value_Stub		IZcPpZcadInput_get_Value_Stub
#endif //#ifndef IAcPpAcadInput_get_Value_Stub

#ifndef IAcPpAcadInput_put_BasePoint
#define IAcPpAcadInput_put_BasePoint		IZcPpZcadInput_put_BasePoint
#endif //#ifndef IAcPpAcadInput_put_BasePoint

#ifndef IAcPpAcadInput_put_BasePoint_Proxy
#define IAcPpAcadInput_put_BasePoint_Proxy		IZcPpZcadInput_put_BasePoint_Proxy
#endif //#ifndef IAcPpAcadInput_put_BasePoint_Proxy

#ifndef IAcPpAcadInput_put_BasePoint_Stub
#define IAcPpAcadInput_put_BasePoint_Stub		IZcPpZcadInput_put_BasePoint_Stub
#endif //#ifndef IAcPpAcadInput_put_BasePoint_Stub

#ifndef IAcPpAcadInput_put_CrOnly
#define IAcPpAcadInput_put_CrOnly		IZcPpZcadInput_put_CrOnly
#endif //#ifndef IAcPpAcadInput_put_CrOnly

#ifndef IAcPpAcadInput_put_CrOnly_Proxy
#define IAcPpAcadInput_put_CrOnly_Proxy		IZcPpZcadInput_put_CrOnly_Proxy
#endif //#ifndef IAcPpAcadInput_put_CrOnly_Proxy

#ifndef IAcPpAcadInput_put_CrOnly_Stub
#define IAcPpAcadInput_put_CrOnly_Stub		IZcPpZcadInput_put_CrOnly_Stub
#endif //#ifndef IAcPpAcadInput_put_CrOnly_Stub

#ifndef IAcPpAcadInput_put_Document
#define IAcPpAcadInput_put_Document		IZcPpZcadInput_put_Document
#endif //#ifndef IAcPpAcadInput_put_Document

#ifndef IAcPpAcadInput_put_Document_Proxy
#define IAcPpAcadInput_put_Document_Proxy		IZcPpZcadInput_put_Document_Proxy
#endif //#ifndef IAcPpAcadInput_put_Document_Proxy

#ifndef IAcPpAcadInput_put_Document_Stub
#define IAcPpAcadInput_put_Document_Stub		IZcPpZcadInput_put_Document_Stub
#endif //#ifndef IAcPpAcadInput_put_Document_Stub

#ifndef IAcPpAcadInput_put_EnableNotification
#define IAcPpAcadInput_put_EnableNotification		IZcPpZcadInput_put_EnableNotification
#endif //#ifndef IAcPpAcadInput_put_EnableNotification

#ifndef IAcPpAcadInput_put_EnableNotification_Proxy
#define IAcPpAcadInput_put_EnableNotification_Proxy		IZcPpZcadInput_put_EnableNotification_Proxy
#endif //#ifndef IAcPpAcadInput_put_EnableNotification_Proxy

#ifndef IAcPpAcadInput_put_EnableNotification_Stub
#define IAcPpAcadInput_put_EnableNotification_Stub		IZcPpZcadInput_put_EnableNotification_Stub
#endif //#ifndef IAcPpAcadInput_put_EnableNotification_Stub

#ifndef IAcPpAcadInput_put_InitGetBit
#define IAcPpAcadInput_put_InitGetBit		IZcPpZcadInput_put_InitGetBit
#endif //#ifndef IAcPpAcadInput_put_InitGetBit

#ifndef IAcPpAcadInput_put_InitGetBit_Proxy
#define IAcPpAcadInput_put_InitGetBit_Proxy		IZcPpZcadInput_put_InitGetBit_Proxy
#endif //#ifndef IAcPpAcadInput_put_InitGetBit_Proxy

#ifndef IAcPpAcadInput_put_InitGetBit_Stub
#define IAcPpAcadInput_put_InitGetBit_Stub		IZcPpZcadInput_put_InitGetBit_Stub
#endif //#ifndef IAcPpAcadInput_put_InitGetBit_Stub

#ifndef IAcPpAcadInput_put_InitGetKword
#define IAcPpAcadInput_put_InitGetKword		IZcPpZcadInput_put_InitGetKword
#endif //#ifndef IAcPpAcadInput_put_InitGetKword

#ifndef IAcPpAcadInput_put_InitGetKword_Proxy
#define IAcPpAcadInput_put_InitGetKword_Proxy		IZcPpZcadInput_put_InitGetKword_Proxy
#endif //#ifndef IAcPpAcadInput_put_InitGetKword_Proxy

#ifndef IAcPpAcadInput_put_InitGetKword_Stub
#define IAcPpAcadInput_put_InitGetKword_Stub		IZcPpZcadInput_put_InitGetKword_Stub
#endif //#ifndef IAcPpAcadInput_put_InitGetKword_Stub

#ifndef IAcPpAcadInput_put_Prompt
#define IAcPpAcadInput_put_Prompt		IZcPpZcadInput_put_Prompt
#endif //#ifndef IAcPpAcadInput_put_Prompt

#ifndef IAcPpAcadInput_put_Prompt2
#define IAcPpAcadInput_put_Prompt2		IZcPpZcadInput_put_Prompt2
#endif //#ifndef IAcPpAcadInput_put_Prompt2

#ifndef IAcPpAcadInput_put_Prompt2_Proxy
#define IAcPpAcadInput_put_Prompt2_Proxy		IZcPpZcadInput_put_Prompt2_Proxy
#endif //#ifndef IAcPpAcadInput_put_Prompt2_Proxy

#ifndef IAcPpAcadInput_put_Prompt2_Stub
#define IAcPpAcadInput_put_Prompt2_Stub		IZcPpZcadInput_put_Prompt2_Stub
#endif //#ifndef IAcPpAcadInput_put_Prompt2_Stub

#ifndef IAcPpAcadInput_put_PromptType
#define IAcPpAcadInput_put_PromptType		IZcPpZcadInput_put_PromptType
#endif //#ifndef IAcPpAcadInput_put_PromptType

#ifndef IAcPpAcadInput_put_PromptType_Proxy
#define IAcPpAcadInput_put_PromptType_Proxy		IZcPpZcadInput_put_PromptType_Proxy
#endif //#ifndef IAcPpAcadInput_put_PromptType_Proxy

#ifndef IAcPpAcadInput_put_PromptType_Stub
#define IAcPpAcadInput_put_PromptType_Stub		IZcPpZcadInput_put_PromptType_Stub
#endif //#ifndef IAcPpAcadInput_put_PromptType_Stub

#ifndef IAcPpAcadInput_put_Prompt_Proxy
#define IAcPpAcadInput_put_Prompt_Proxy		IZcPpZcadInput_put_Prompt_Proxy
#endif //#ifndef IAcPpAcadInput_put_Prompt_Proxy

#ifndef IAcPpAcadInput_put_Prompt_Stub
#define IAcPpAcadInput_put_Prompt_Stub		IZcPpZcadInput_put_Prompt_Stub
#endif //#ifndef IAcPpAcadInput_put_Prompt_Stub

#ifndef IAcPpAcadInput_put_Status
#define IAcPpAcadInput_put_Status		IZcPpZcadInput_put_Status
#endif //#ifndef IAcPpAcadInput_put_Status

#ifndef IAcPpAcadInput_put_Status_Proxy
#define IAcPpAcadInput_put_Status_Proxy		IZcPpZcadInput_put_Status_Proxy
#endif //#ifndef IAcPpAcadInput_put_Status_Proxy

#ifndef IAcPpAcadInput_put_Status_Stub
#define IAcPpAcadInput_put_Status_Stub		IZcPpZcadInput_put_Status_Stub
#endif //#ifndef IAcPpAcadInput_put_Status_Stub

#ifndef IAcPpAcadInput_put_Value
#define IAcPpAcadInput_put_Value		IZcPpZcadInput_put_Value
#endif //#ifndef IAcPpAcadInput_put_Value

#ifndef IAcPpAcadInput_put_Value_Proxy
#define IAcPpAcadInput_put_Value_Proxy		IZcPpZcadInput_put_Value_Proxy
#endif //#ifndef IAcPpAcadInput_put_Value_Proxy

#ifndef IAcPpAcadInput_put_Value_Stub
#define IAcPpAcadInput_put_Value_Stub		IZcPpZcadInput_put_Value_Stub
#endif //#ifndef IAcPpAcadInput_put_Value_Stub

#ifndef IAcPpNavTree
#define IAcPpNavTree		IZcPpNavTree
#endif //#ifndef IAcPpNavTree

#ifndef IAcPpNavTreeCmdBtn
#define IAcPpNavTreeCmdBtn		IZcPpNavTreeCmdBtn
#endif //#ifndef IAcPpNavTreeCmdBtn

#ifndef IAcPpNavTreeCmdBtnCollection
#define IAcPpNavTreeCmdBtnCollection		IZcPpNavTreeCmdBtnCollection
#endif //#ifndef IAcPpNavTreeCmdBtnCollection

#ifndef IAcPpNavTreeCmdBtnCollectionIter
#define IAcPpNavTreeCmdBtnCollectionIter		IZcPpNavTreeCmdBtnCollectionIter
#endif //#ifndef IAcPpNavTreeCmdBtnCollectionIter

#ifndef IAcPpNavTreeCmdBtnCollectionIterVtbl
#define IAcPpNavTreeCmdBtnCollectionIterVtbl		IZcPpNavTreeCmdBtnCollectionIterVtbl
#endif //#ifndef IAcPpNavTreeCmdBtnCollectionIterVtbl

#ifndef IAcPpNavTreeCmdBtnCollectionIter_AddRef
#define IAcPpNavTreeCmdBtnCollectionIter_AddRef		IZcPpNavTreeCmdBtnCollectionIter_AddRef
#endif //#ifndef IAcPpNavTreeCmdBtnCollectionIter_AddRef

#ifndef IAcPpNavTreeCmdBtnCollectionIter_Current
#define IAcPpNavTreeCmdBtnCollectionIter_Current		IZcPpNavTreeCmdBtnCollectionIter_Current
#endif //#ifndef IAcPpNavTreeCmdBtnCollectionIter_Current

#ifndef IAcPpNavTreeCmdBtnCollectionIter_Current_Proxy
#define IAcPpNavTreeCmdBtnCollectionIter_Current_Proxy		IZcPpNavTreeCmdBtnCollectionIter_Current_Proxy
#endif //#ifndef IAcPpNavTreeCmdBtnCollectionIter_Current_Proxy

#ifndef IAcPpNavTreeCmdBtnCollectionIter_Current_Stub
#define IAcPpNavTreeCmdBtnCollectionIter_Current_Stub		IZcPpNavTreeCmdBtnCollectionIter_Current_Stub
#endif //#ifndef IAcPpNavTreeCmdBtnCollectionIter_Current_Stub

#ifndef IAcPpNavTreeCmdBtnCollectionIter_Done
#define IAcPpNavTreeCmdBtnCollectionIter_Done		IZcPpNavTreeCmdBtnCollectionIter_Done
#endif //#ifndef IAcPpNavTreeCmdBtnCollectionIter_Done

#ifndef IAcPpNavTreeCmdBtnCollectionIter_Done_Proxy
#define IAcPpNavTreeCmdBtnCollectionIter_Done_Proxy		IZcPpNavTreeCmdBtnCollectionIter_Done_Proxy
#endif //#ifndef IAcPpNavTreeCmdBtnCollectionIter_Done_Proxy

#ifndef IAcPpNavTreeCmdBtnCollectionIter_Done_Stub
#define IAcPpNavTreeCmdBtnCollectionIter_Done_Stub		IZcPpNavTreeCmdBtnCollectionIter_Done_Stub
#endif //#ifndef IAcPpNavTreeCmdBtnCollectionIter_Done_Stub

#ifndef IAcPpNavTreeCmdBtnCollectionIter_Next
#define IAcPpNavTreeCmdBtnCollectionIter_Next		IZcPpNavTreeCmdBtnCollectionIter_Next
#endif //#ifndef IAcPpNavTreeCmdBtnCollectionIter_Next

#ifndef IAcPpNavTreeCmdBtnCollectionIter_Next_Proxy
#define IAcPpNavTreeCmdBtnCollectionIter_Next_Proxy		IZcPpNavTreeCmdBtnCollectionIter_Next_Proxy
#endif //#ifndef IAcPpNavTreeCmdBtnCollectionIter_Next_Proxy

#ifndef IAcPpNavTreeCmdBtnCollectionIter_Next_Stub
#define IAcPpNavTreeCmdBtnCollectionIter_Next_Stub		IZcPpNavTreeCmdBtnCollectionIter_Next_Stub
#endif //#ifndef IAcPpNavTreeCmdBtnCollectionIter_Next_Stub

#ifndef IAcPpNavTreeCmdBtnCollectionIter_QueryInterface
#define IAcPpNavTreeCmdBtnCollectionIter_QueryInterface		IZcPpNavTreeCmdBtnCollectionIter_QueryInterface
#endif //#ifndef IAcPpNavTreeCmdBtnCollectionIter_QueryInterface

#ifndef IAcPpNavTreeCmdBtnCollectionIter_Release
#define IAcPpNavTreeCmdBtnCollectionIter_Release		IZcPpNavTreeCmdBtnCollectionIter_Release
#endif //#ifndef IAcPpNavTreeCmdBtnCollectionIter_Release

#ifndef IAcPpNavTreeCmdBtnCollectionIter_Start
#define IAcPpNavTreeCmdBtnCollectionIter_Start		IZcPpNavTreeCmdBtnCollectionIter_Start
#endif //#ifndef IAcPpNavTreeCmdBtnCollectionIter_Start

#ifndef IAcPpNavTreeCmdBtnCollectionIter_Start_Proxy
#define IAcPpNavTreeCmdBtnCollectionIter_Start_Proxy		IZcPpNavTreeCmdBtnCollectionIter_Start_Proxy
#endif //#ifndef IAcPpNavTreeCmdBtnCollectionIter_Start_Proxy

#ifndef IAcPpNavTreeCmdBtnCollectionIter_Start_Stub
#define IAcPpNavTreeCmdBtnCollectionIter_Start_Stub		IZcPpNavTreeCmdBtnCollectionIter_Start_Stub
#endif //#ifndef IAcPpNavTreeCmdBtnCollectionIter_Start_Stub

#ifndef IAcPpNavTreeCmdBtnCollectionVtbl
#define IAcPpNavTreeCmdBtnCollectionVtbl		IZcPpNavTreeCmdBtnCollectionVtbl
#endif //#ifndef IAcPpNavTreeCmdBtnCollectionVtbl

#ifndef IAcPpNavTreeCmdBtnCollection_AddButton
#define IAcPpNavTreeCmdBtnCollection_AddButton		IZcPpNavTreeCmdBtnCollection_AddButton
#endif //#ifndef IAcPpNavTreeCmdBtnCollection_AddButton

#ifndef IAcPpNavTreeCmdBtnCollection_AddButton_Proxy
#define IAcPpNavTreeCmdBtnCollection_AddButton_Proxy		IZcPpNavTreeCmdBtnCollection_AddButton_Proxy
#endif //#ifndef IAcPpNavTreeCmdBtnCollection_AddButton_Proxy

#ifndef IAcPpNavTreeCmdBtnCollection_AddButton_Stub
#define IAcPpNavTreeCmdBtnCollection_AddButton_Stub		IZcPpNavTreeCmdBtnCollection_AddButton_Stub
#endif //#ifndef IAcPpNavTreeCmdBtnCollection_AddButton_Stub

#ifndef IAcPpNavTreeCmdBtnCollection_AddRef
#define IAcPpNavTreeCmdBtnCollection_AddRef		IZcPpNavTreeCmdBtnCollection_AddRef
#endif //#ifndef IAcPpNavTreeCmdBtnCollection_AddRef

#ifndef IAcPpNavTreeCmdBtnCollection_DeleteAllButtons
#define IAcPpNavTreeCmdBtnCollection_DeleteAllButtons		IZcPpNavTreeCmdBtnCollection_DeleteAllButtons
#endif //#ifndef IAcPpNavTreeCmdBtnCollection_DeleteAllButtons

#ifndef IAcPpNavTreeCmdBtnCollection_DeleteAllButtons_Proxy
#define IAcPpNavTreeCmdBtnCollection_DeleteAllButtons_Proxy		IZcPpNavTreeCmdBtnCollection_DeleteAllButtons_Proxy
#endif //#ifndef IAcPpNavTreeCmdBtnCollection_DeleteAllButtons_Proxy

#ifndef IAcPpNavTreeCmdBtnCollection_DeleteAllButtons_Stub
#define IAcPpNavTreeCmdBtnCollection_DeleteAllButtons_Stub		IZcPpNavTreeCmdBtnCollection_DeleteAllButtons_Stub
#endif //#ifndef IAcPpNavTreeCmdBtnCollection_DeleteAllButtons_Stub

#ifndef IAcPpNavTreeCmdBtnCollection_DeleteButton
#define IAcPpNavTreeCmdBtnCollection_DeleteButton		IZcPpNavTreeCmdBtnCollection_DeleteButton
#endif //#ifndef IAcPpNavTreeCmdBtnCollection_DeleteButton

#ifndef IAcPpNavTreeCmdBtnCollection_DeleteButton_Proxy
#define IAcPpNavTreeCmdBtnCollection_DeleteButton_Proxy		IZcPpNavTreeCmdBtnCollection_DeleteButton_Proxy
#endif //#ifndef IAcPpNavTreeCmdBtnCollection_DeleteButton_Proxy

#ifndef IAcPpNavTreeCmdBtnCollection_DeleteButton_Stub
#define IAcPpNavTreeCmdBtnCollection_DeleteButton_Stub		IZcPpNavTreeCmdBtnCollection_DeleteButton_Stub
#endif //#ifndef IAcPpNavTreeCmdBtnCollection_DeleteButton_Stub

#ifndef IAcPpNavTreeCmdBtnCollection_GetCmdBtnCollectionIter
#define IAcPpNavTreeCmdBtnCollection_GetCmdBtnCollectionIter		IZcPpNavTreeCmdBtnCollection_GetCmdBtnCollectionIter
#endif //#ifndef IAcPpNavTreeCmdBtnCollection_GetCmdBtnCollectionIter

#ifndef IAcPpNavTreeCmdBtnCollection_GetCmdBtnCollectionIter_Proxy
#define IAcPpNavTreeCmdBtnCollection_GetCmdBtnCollectionIter_Proxy		IZcPpNavTreeCmdBtnCollection_GetCmdBtnCollectionIter_Proxy
#endif //#ifndef IAcPpNavTreeCmdBtnCollection_GetCmdBtnCollectionIter_Proxy

#ifndef IAcPpNavTreeCmdBtnCollection_GetCmdBtnCollectionIter_Stub
#define IAcPpNavTreeCmdBtnCollection_GetCmdBtnCollectionIter_Stub		IZcPpNavTreeCmdBtnCollection_GetCmdBtnCollectionIter_Stub
#endif //#ifndef IAcPpNavTreeCmdBtnCollection_GetCmdBtnCollectionIter_Stub

#ifndef IAcPpNavTreeCmdBtnCollection_QueryInterface
#define IAcPpNavTreeCmdBtnCollection_QueryInterface		IZcPpNavTreeCmdBtnCollection_QueryInterface
#endif //#ifndef IAcPpNavTreeCmdBtnCollection_QueryInterface

#ifndef IAcPpNavTreeCmdBtnCollection_Release
#define IAcPpNavTreeCmdBtnCollection_Release		IZcPpNavTreeCmdBtnCollection_Release
#endif //#ifndef IAcPpNavTreeCmdBtnCollection_Release

#ifndef IAcPpNavTreeCmdBtnVtbl
#define IAcPpNavTreeCmdBtnVtbl		IZcPpNavTreeCmdBtnVtbl
#endif //#ifndef IAcPpNavTreeCmdBtnVtbl

#ifndef IAcPpNavTreeCmdBtn_AddRef
#define IAcPpNavTreeCmdBtn_AddRef		IZcPpNavTreeCmdBtn_AddRef
#endif //#ifndef IAcPpNavTreeCmdBtn_AddRef

#ifndef IAcPpNavTreeCmdBtn_Execute
#define IAcPpNavTreeCmdBtn_Execute		IZcPpNavTreeCmdBtn_Execute
#endif //#ifndef IAcPpNavTreeCmdBtn_Execute

#ifndef IAcPpNavTreeCmdBtn_Execute_Proxy
#define IAcPpNavTreeCmdBtn_Execute_Proxy		IZcPpNavTreeCmdBtn_Execute_Proxy
#endif //#ifndef IAcPpNavTreeCmdBtn_Execute_Proxy

#ifndef IAcPpNavTreeCmdBtn_Execute_Stub
#define IAcPpNavTreeCmdBtn_Execute_Stub		IZcPpNavTreeCmdBtn_Execute_Stub
#endif //#ifndef IAcPpNavTreeCmdBtn_Execute_Stub

#ifndef IAcPpNavTreeCmdBtn_GetBtnImage
#define IAcPpNavTreeCmdBtn_GetBtnImage		IZcPpNavTreeCmdBtn_GetBtnImage
#endif //#ifndef IAcPpNavTreeCmdBtn_GetBtnImage

#ifndef IAcPpNavTreeCmdBtn_GetBtnImage_Proxy
#define IAcPpNavTreeCmdBtn_GetBtnImage_Proxy		IZcPpNavTreeCmdBtn_GetBtnImage_Proxy
#endif //#ifndef IAcPpNavTreeCmdBtn_GetBtnImage_Proxy

#ifndef IAcPpNavTreeCmdBtn_GetBtnImage_Stub
#define IAcPpNavTreeCmdBtn_GetBtnImage_Stub		IZcPpNavTreeCmdBtn_GetBtnImage_Stub
#endif //#ifndef IAcPpNavTreeCmdBtn_GetBtnImage_Stub

#ifndef IAcPpNavTreeCmdBtn_QueryInterface
#define IAcPpNavTreeCmdBtn_QueryInterface		IZcPpNavTreeCmdBtn_QueryInterface
#endif //#ifndef IAcPpNavTreeCmdBtn_QueryInterface

#ifndef IAcPpNavTreeCmdBtn_Release
#define IAcPpNavTreeCmdBtn_Release		IZcPpNavTreeCmdBtn_Release
#endif //#ifndef IAcPpNavTreeCmdBtn_Release

#ifndef IAcPpNavTreeCmdBtn_get_Name
#define IAcPpNavTreeCmdBtn_get_Name		IZcPpNavTreeCmdBtn_get_Name
#endif //#ifndef IAcPpNavTreeCmdBtn_get_Name

#ifndef IAcPpNavTreeCmdBtn_get_Name_Proxy
#define IAcPpNavTreeCmdBtn_get_Name_Proxy		IZcPpNavTreeCmdBtn_get_Name_Proxy
#endif //#ifndef IAcPpNavTreeCmdBtn_get_Name_Proxy

#ifndef IAcPpNavTreeCmdBtn_get_Name_Stub
#define IAcPpNavTreeCmdBtn_get_Name_Stub		IZcPpNavTreeCmdBtn_get_Name_Stub
#endif //#ifndef IAcPpNavTreeCmdBtn_get_Name_Stub

#ifndef IAcPpNavTreeEvents
#define IAcPpNavTreeEvents		IZcPpNavTreeEvents
#endif //#ifndef IAcPpNavTreeEvents

#ifndef IAcPpNavTreeEventsVtbl
#define IAcPpNavTreeEventsVtbl		IZcPpNavTreeEventsVtbl
#endif //#ifndef IAcPpNavTreeEventsVtbl

#ifndef IAcPpNavTreeEvents_AddRef
#define IAcPpNavTreeEvents_AddRef		IZcPpNavTreeEvents_AddRef
#endif //#ifndef IAcPpNavTreeEvents_AddRef

#ifndef IAcPpNavTreeEvents_OnDblClickTreeItem
#define IAcPpNavTreeEvents_OnDblClickTreeItem		IZcPpNavTreeEvents_OnDblClickTreeItem
#endif //#ifndef IAcPpNavTreeEvents_OnDblClickTreeItem

#ifndef IAcPpNavTreeEvents_OnDblClickTreeItem_Proxy
#define IAcPpNavTreeEvents_OnDblClickTreeItem_Proxy		IZcPpNavTreeEvents_OnDblClickTreeItem_Proxy
#endif //#ifndef IAcPpNavTreeEvents_OnDblClickTreeItem_Proxy

#ifndef IAcPpNavTreeEvents_OnDblClickTreeItem_Stub
#define IAcPpNavTreeEvents_OnDblClickTreeItem_Stub		IZcPpNavTreeEvents_OnDblClickTreeItem_Stub
#endif //#ifndef IAcPpNavTreeEvents_OnDblClickTreeItem_Stub

#ifndef IAcPpNavTreeEvents_OnSelectionChanged
#define IAcPpNavTreeEvents_OnSelectionChanged		IZcPpNavTreeEvents_OnSelectionChanged
#endif //#ifndef IAcPpNavTreeEvents_OnSelectionChanged

#ifndef IAcPpNavTreeEvents_OnSelectionChanged_Proxy
#define IAcPpNavTreeEvents_OnSelectionChanged_Proxy		IZcPpNavTreeEvents_OnSelectionChanged_Proxy
#endif //#ifndef IAcPpNavTreeEvents_OnSelectionChanged_Proxy

#ifndef IAcPpNavTreeEvents_OnSelectionChanged_Stub
#define IAcPpNavTreeEvents_OnSelectionChanged_Stub		IZcPpNavTreeEvents_OnSelectionChanged_Stub
#endif //#ifndef IAcPpNavTreeEvents_OnSelectionChanged_Stub

#ifndef IAcPpNavTreeEvents_QueryInterface
#define IAcPpNavTreeEvents_QueryInterface		IZcPpNavTreeEvents_QueryInterface
#endif //#ifndef IAcPpNavTreeEvents_QueryInterface

#ifndef IAcPpNavTreeEvents_Release
#define IAcPpNavTreeEvents_Release		IZcPpNavTreeEvents_Release
#endif //#ifndef IAcPpNavTreeEvents_Release

#ifndef IAcPpNavTreeNode
#define IAcPpNavTreeNode		IZcPpNavTreeNode
#endif //#ifndef IAcPpNavTreeNode

#ifndef IAcPpNavTreeNodeCollection
#define IAcPpNavTreeNodeCollection		IZcPpNavTreeNodeCollection
#endif //#ifndef IAcPpNavTreeNodeCollection

#ifndef IAcPpNavTreeNodeCollectionIter
#define IAcPpNavTreeNodeCollectionIter		IZcPpNavTreeNodeCollectionIter
#endif //#ifndef IAcPpNavTreeNodeCollectionIter

#ifndef IAcPpNavTreeNodeCollectionIterVtbl
#define IAcPpNavTreeNodeCollectionIterVtbl		IZcPpNavTreeNodeCollectionIterVtbl
#endif //#ifndef IAcPpNavTreeNodeCollectionIterVtbl

#ifndef IAcPpNavTreeNodeCollectionIter_AddRef
#define IAcPpNavTreeNodeCollectionIter_AddRef		IZcPpNavTreeNodeCollectionIter_AddRef
#endif //#ifndef IAcPpNavTreeNodeCollectionIter_AddRef

#ifndef IAcPpNavTreeNodeCollectionIter_Current
#define IAcPpNavTreeNodeCollectionIter_Current		IZcPpNavTreeNodeCollectionIter_Current
#endif //#ifndef IAcPpNavTreeNodeCollectionIter_Current

#ifndef IAcPpNavTreeNodeCollectionIter_Current_Proxy
#define IAcPpNavTreeNodeCollectionIter_Current_Proxy		IZcPpNavTreeNodeCollectionIter_Current_Proxy
#endif //#ifndef IAcPpNavTreeNodeCollectionIter_Current_Proxy

#ifndef IAcPpNavTreeNodeCollectionIter_Current_Stub
#define IAcPpNavTreeNodeCollectionIter_Current_Stub		IZcPpNavTreeNodeCollectionIter_Current_Stub
#endif //#ifndef IAcPpNavTreeNodeCollectionIter_Current_Stub

#ifndef IAcPpNavTreeNodeCollectionIter_Done
#define IAcPpNavTreeNodeCollectionIter_Done		IZcPpNavTreeNodeCollectionIter_Done
#endif //#ifndef IAcPpNavTreeNodeCollectionIter_Done

#ifndef IAcPpNavTreeNodeCollectionIter_Done_Proxy
#define IAcPpNavTreeNodeCollectionIter_Done_Proxy		IZcPpNavTreeNodeCollectionIter_Done_Proxy
#endif //#ifndef IAcPpNavTreeNodeCollectionIter_Done_Proxy

#ifndef IAcPpNavTreeNodeCollectionIter_Done_Stub
#define IAcPpNavTreeNodeCollectionIter_Done_Stub		IZcPpNavTreeNodeCollectionIter_Done_Stub
#endif //#ifndef IAcPpNavTreeNodeCollectionIter_Done_Stub

#ifndef IAcPpNavTreeNodeCollectionIter_Next
#define IAcPpNavTreeNodeCollectionIter_Next		IZcPpNavTreeNodeCollectionIter_Next
#endif //#ifndef IAcPpNavTreeNodeCollectionIter_Next

#ifndef IAcPpNavTreeNodeCollectionIter_Next_Proxy
#define IAcPpNavTreeNodeCollectionIter_Next_Proxy		IZcPpNavTreeNodeCollectionIter_Next_Proxy
#endif //#ifndef IAcPpNavTreeNodeCollectionIter_Next_Proxy

#ifndef IAcPpNavTreeNodeCollectionIter_Next_Stub
#define IAcPpNavTreeNodeCollectionIter_Next_Stub		IZcPpNavTreeNodeCollectionIter_Next_Stub
#endif //#ifndef IAcPpNavTreeNodeCollectionIter_Next_Stub

#ifndef IAcPpNavTreeNodeCollectionIter_QueryInterface
#define IAcPpNavTreeNodeCollectionIter_QueryInterface		IZcPpNavTreeNodeCollectionIter_QueryInterface
#endif //#ifndef IAcPpNavTreeNodeCollectionIter_QueryInterface

#ifndef IAcPpNavTreeNodeCollectionIter_Release
#define IAcPpNavTreeNodeCollectionIter_Release		IZcPpNavTreeNodeCollectionIter_Release
#endif //#ifndef IAcPpNavTreeNodeCollectionIter_Release

#ifndef IAcPpNavTreeNodeCollectionIter_Start
#define IAcPpNavTreeNodeCollectionIter_Start		IZcPpNavTreeNodeCollectionIter_Start
#endif //#ifndef IAcPpNavTreeNodeCollectionIter_Start

#ifndef IAcPpNavTreeNodeCollectionIter_Start_Proxy
#define IAcPpNavTreeNodeCollectionIter_Start_Proxy		IZcPpNavTreeNodeCollectionIter_Start_Proxy
#endif //#ifndef IAcPpNavTreeNodeCollectionIter_Start_Proxy

#ifndef IAcPpNavTreeNodeCollectionIter_Start_Stub
#define IAcPpNavTreeNodeCollectionIter_Start_Stub		IZcPpNavTreeNodeCollectionIter_Start_Stub
#endif //#ifndef IAcPpNavTreeNodeCollectionIter_Start_Stub

#ifndef IAcPpNavTreeNodeCollectionVtbl
#define IAcPpNavTreeNodeCollectionVtbl		IZcPpNavTreeNodeCollectionVtbl
#endif //#ifndef IAcPpNavTreeNodeCollectionVtbl

#ifndef IAcPpNavTreeNodeCollection_AddNode
#define IAcPpNavTreeNodeCollection_AddNode		IZcPpNavTreeNodeCollection_AddNode
#endif //#ifndef IAcPpNavTreeNodeCollection_AddNode

#ifndef IAcPpNavTreeNodeCollection_AddNode_Proxy
#define IAcPpNavTreeNodeCollection_AddNode_Proxy		IZcPpNavTreeNodeCollection_AddNode_Proxy
#endif //#ifndef IAcPpNavTreeNodeCollection_AddNode_Proxy

#ifndef IAcPpNavTreeNodeCollection_AddNode_Stub
#define IAcPpNavTreeNodeCollection_AddNode_Stub		IZcPpNavTreeNodeCollection_AddNode_Stub
#endif //#ifndef IAcPpNavTreeNodeCollection_AddNode_Stub

#ifndef IAcPpNavTreeNodeCollection_AddRef
#define IAcPpNavTreeNodeCollection_AddRef		IZcPpNavTreeNodeCollection_AddRef
#endif //#ifndef IAcPpNavTreeNodeCollection_AddRef

#ifndef IAcPpNavTreeNodeCollection_DeleteAllNodes
#define IAcPpNavTreeNodeCollection_DeleteAllNodes		IZcPpNavTreeNodeCollection_DeleteAllNodes
#endif //#ifndef IAcPpNavTreeNodeCollection_DeleteAllNodes

#ifndef IAcPpNavTreeNodeCollection_DeleteAllNodes_Proxy
#define IAcPpNavTreeNodeCollection_DeleteAllNodes_Proxy		IZcPpNavTreeNodeCollection_DeleteAllNodes_Proxy
#endif //#ifndef IAcPpNavTreeNodeCollection_DeleteAllNodes_Proxy

#ifndef IAcPpNavTreeNodeCollection_DeleteAllNodes_Stub
#define IAcPpNavTreeNodeCollection_DeleteAllNodes_Stub		IZcPpNavTreeNodeCollection_DeleteAllNodes_Stub
#endif //#ifndef IAcPpNavTreeNodeCollection_DeleteAllNodes_Stub

#ifndef IAcPpNavTreeNodeCollection_DeleteNode
#define IAcPpNavTreeNodeCollection_DeleteNode		IZcPpNavTreeNodeCollection_DeleteNode
#endif //#ifndef IAcPpNavTreeNodeCollection_DeleteNode

#ifndef IAcPpNavTreeNodeCollection_DeleteNode_Proxy
#define IAcPpNavTreeNodeCollection_DeleteNode_Proxy		IZcPpNavTreeNodeCollection_DeleteNode_Proxy
#endif //#ifndef IAcPpNavTreeNodeCollection_DeleteNode_Proxy

#ifndef IAcPpNavTreeNodeCollection_DeleteNode_Stub
#define IAcPpNavTreeNodeCollection_DeleteNode_Stub		IZcPpNavTreeNodeCollection_DeleteNode_Stub
#endif //#ifndef IAcPpNavTreeNodeCollection_DeleteNode_Stub

#ifndef IAcPpNavTreeNodeCollection_GetNodeCollectionIter
#define IAcPpNavTreeNodeCollection_GetNodeCollectionIter		IZcPpNavTreeNodeCollection_GetNodeCollectionIter
#endif //#ifndef IAcPpNavTreeNodeCollection_GetNodeCollectionIter

#ifndef IAcPpNavTreeNodeCollection_GetNodeCollectionIter_Proxy
#define IAcPpNavTreeNodeCollection_GetNodeCollectionIter_Proxy		IZcPpNavTreeNodeCollection_GetNodeCollectionIter_Proxy
#endif //#ifndef IAcPpNavTreeNodeCollection_GetNodeCollectionIter_Proxy

#ifndef IAcPpNavTreeNodeCollection_GetNodeCollectionIter_Stub
#define IAcPpNavTreeNodeCollection_GetNodeCollectionIter_Stub		IZcPpNavTreeNodeCollection_GetNodeCollectionIter_Stub
#endif //#ifndef IAcPpNavTreeNodeCollection_GetNodeCollectionIter_Stub

#ifndef IAcPpNavTreeNodeCollection_QueryInterface
#define IAcPpNavTreeNodeCollection_QueryInterface		IZcPpNavTreeNodeCollection_QueryInterface
#endif //#ifndef IAcPpNavTreeNodeCollection_QueryInterface

#ifndef IAcPpNavTreeNodeCollection_Release
#define IAcPpNavTreeNodeCollection_Release		IZcPpNavTreeNodeCollection_Release
#endif //#ifndef IAcPpNavTreeNodeCollection_Release

#ifndef IAcPpNavTreeNodeVtbl
#define IAcPpNavTreeNodeVtbl		IZcPpNavTreeNodeVtbl
#endif //#ifndef IAcPpNavTreeNodeVtbl

#ifndef IAcPpNavTreeNode_AddRef
#define IAcPpNavTreeNode_AddRef		IZcPpNavTreeNode_AddRef
#endif //#ifndef IAcPpNavTreeNode_AddRef

#ifndef IAcPpNavTreeNode_GetObject
#define IAcPpNavTreeNode_GetObject		IZcPpNavTreeNode_GetObject
#endif //#ifndef IAcPpNavTreeNode_GetObject

#ifndef IAcPpNavTreeNode_GetObject_Proxy
#define IAcPpNavTreeNode_GetObject_Proxy		IZcPpNavTreeNode_GetObject_Proxy
#endif //#ifndef IAcPpNavTreeNode_GetObject_Proxy

#ifndef IAcPpNavTreeNode_GetObject_Stub
#define IAcPpNavTreeNode_GetObject_Stub		IZcPpNavTreeNode_GetObject_Stub
#endif //#ifndef IAcPpNavTreeNode_GetObject_Stub

#ifndef IAcPpNavTreeNode_QueryInterface
#define IAcPpNavTreeNode_QueryInterface		IZcPpNavTreeNode_QueryInterface
#endif //#ifndef IAcPpNavTreeNode_QueryInterface

#ifndef IAcPpNavTreeNode_Release
#define IAcPpNavTreeNode_Release		IZcPpNavTreeNode_Release
#endif //#ifndef IAcPpNavTreeNode_Release

#ifndef IAcPpNavTreeNode_get_ID
#define IAcPpNavTreeNode_get_ID		IZcPpNavTreeNode_get_ID
#endif //#ifndef IAcPpNavTreeNode_get_ID

#ifndef IAcPpNavTreeNode_get_ID_Proxy
#define IAcPpNavTreeNode_get_ID_Proxy		IZcPpNavTreeNode_get_ID_Proxy
#endif //#ifndef IAcPpNavTreeNode_get_ID_Proxy

#ifndef IAcPpNavTreeNode_get_ID_Stub
#define IAcPpNavTreeNode_get_ID_Stub		IZcPpNavTreeNode_get_ID_Stub
#endif //#ifndef IAcPpNavTreeNode_get_ID_Stub

#ifndef IAcPpNavTreeNode_get_Label
#define IAcPpNavTreeNode_get_Label		IZcPpNavTreeNode_get_Label
#endif //#ifndef IAcPpNavTreeNode_get_Label

#ifndef IAcPpNavTreeNode_get_Label_Proxy
#define IAcPpNavTreeNode_get_Label_Proxy		IZcPpNavTreeNode_get_Label_Proxy
#endif //#ifndef IAcPpNavTreeNode_get_Label_Proxy

#ifndef IAcPpNavTreeNode_get_Label_Stub
#define IAcPpNavTreeNode_get_Label_Stub		IZcPpNavTreeNode_get_Label_Stub
#endif //#ifndef IAcPpNavTreeNode_get_Label_Stub

#ifndef IAcPpNavTreeNode_get_LeftIconRes
#define IAcPpNavTreeNode_get_LeftIconRes		IZcPpNavTreeNode_get_LeftIconRes
#endif //#ifndef IAcPpNavTreeNode_get_LeftIconRes

#ifndef IAcPpNavTreeNode_get_LeftIconResType
#define IAcPpNavTreeNode_get_LeftIconResType		IZcPpNavTreeNode_get_LeftIconResType
#endif //#ifndef IAcPpNavTreeNode_get_LeftIconResType

#ifndef IAcPpNavTreeNode_get_LeftIconResType_Proxy
#define IAcPpNavTreeNode_get_LeftIconResType_Proxy		IZcPpNavTreeNode_get_LeftIconResType_Proxy
#endif //#ifndef IAcPpNavTreeNode_get_LeftIconResType_Proxy

#ifndef IAcPpNavTreeNode_get_LeftIconResType_Stub
#define IAcPpNavTreeNode_get_LeftIconResType_Stub		IZcPpNavTreeNode_get_LeftIconResType_Stub
#endif //#ifndef IAcPpNavTreeNode_get_LeftIconResType_Stub

#ifndef IAcPpNavTreeNode_get_LeftIconRes_Proxy
#define IAcPpNavTreeNode_get_LeftIconRes_Proxy		IZcPpNavTreeNode_get_LeftIconRes_Proxy
#endif //#ifndef IAcPpNavTreeNode_get_LeftIconRes_Proxy

#ifndef IAcPpNavTreeNode_get_LeftIconRes_Stub
#define IAcPpNavTreeNode_get_LeftIconRes_Stub		IZcPpNavTreeNode_get_LeftIconRes_Stub
#endif //#ifndef IAcPpNavTreeNode_get_LeftIconRes_Stub

#ifndef IAcPpNavTreeNode_get_ParentID
#define IAcPpNavTreeNode_get_ParentID		IZcPpNavTreeNode_get_ParentID
#endif //#ifndef IAcPpNavTreeNode_get_ParentID

#ifndef IAcPpNavTreeNode_get_ParentID_Proxy
#define IAcPpNavTreeNode_get_ParentID_Proxy		IZcPpNavTreeNode_get_ParentID_Proxy
#endif //#ifndef IAcPpNavTreeNode_get_ParentID_Proxy

#ifndef IAcPpNavTreeNode_get_ParentID_Stub
#define IAcPpNavTreeNode_get_ParentID_Stub		IZcPpNavTreeNode_get_ParentID_Stub
#endif //#ifndef IAcPpNavTreeNode_get_ParentID_Stub

#ifndef IAcPpNavTreeVtbl
#define IAcPpNavTreeVtbl		IZcPpNavTreeVtbl
#endif //#ifndef IAcPpNavTreeVtbl

#ifndef IAcPpNavTree_AddRef
#define IAcPpNavTree_AddRef		IZcPpNavTree_AddRef
#endif //#ifndef IAcPpNavTree_AddRef

#ifndef IAcPpNavTree_QueryInterface
#define IAcPpNavTree_QueryInterface		IZcPpNavTree_QueryInterface
#endif //#ifndef IAcPpNavTree_QueryInterface

#ifndef IAcPpNavTree_Release
#define IAcPpNavTree_Release		IZcPpNavTree_Release
#endif //#ifndef IAcPpNavTree_Release

#ifndef IAcPpNavTree_Reset
#define IAcPpNavTree_Reset		IZcPpNavTree_Reset
#endif //#ifndef IAcPpNavTree_Reset

#ifndef IAcPpNavTree_Reset_Proxy
#define IAcPpNavTree_Reset_Proxy		IZcPpNavTree_Reset_Proxy
#endif //#ifndef IAcPpNavTree_Reset_Proxy

#ifndef IAcPpNavTree_Reset_Stub
#define IAcPpNavTree_Reset_Stub		IZcPpNavTree_Reset_Stub
#endif //#ifndef IAcPpNavTree_Reset_Stub

#ifndef IAcPpPalette
#define IAcPpPalette		IZcPpPalette
#endif //#ifndef IAcPpPalette

#ifndef IAcPpPalette2
#define IAcPpPalette2		IZcPpPalette2
#endif //#ifndef IAcPpPalette2

#ifndef IAcPpPalette2Vtbl
#define IAcPpPalette2Vtbl		IZcPpPalette2Vtbl
#endif //#ifndef IAcPpPalette2Vtbl

#ifndef IAcPpPalette2_AddRef
#define IAcPpPalette2_AddRef		IZcPpPalette2_AddRef
#endif //#ifndef IAcPpPalette2_AddRef

#ifndef IAcPpPalette2_QueryInterface
#define IAcPpPalette2_QueryInterface		IZcPpPalette2_QueryInterface
#endif //#ifndef IAcPpPalette2_QueryInterface

#ifndef IAcPpPalette2_Release
#define IAcPpPalette2_Release		IZcPpPalette2_Release
#endif //#ifndef IAcPpPalette2_Release

#ifndef IAcPpPalette2_get_NavTree
#define IAcPpPalette2_get_NavTree		IZcPpPalette2_get_NavTree
#endif //#ifndef IAcPpPalette2_get_NavTree

#ifndef IAcPpPalette2_get_NavTree_Proxy
#define IAcPpPalette2_get_NavTree_Proxy		IZcPpPalette2_get_NavTree_Proxy
#endif //#ifndef IAcPpPalette2_get_NavTree_Proxy

#ifndef IAcPpPalette2_get_NavTree_Stub
#define IAcPpPalette2_get_NavTree_Stub		IZcPpPalette2_get_NavTree_Stub
#endif //#ifndef IAcPpPalette2_get_NavTree_Stub

#ifndef IAcPpPalette2_put_NavTree
#define IAcPpPalette2_put_NavTree		IZcPpPalette2_put_NavTree
#endif //#ifndef IAcPpPalette2_put_NavTree

#ifndef IAcPpPalette2_put_NavTree_Proxy
#define IAcPpPalette2_put_NavTree_Proxy		IZcPpPalette2_put_NavTree_Proxy
#endif //#ifndef IAcPpPalette2_put_NavTree_Proxy

#ifndef IAcPpPalette2_put_NavTree_Stub
#define IAcPpPalette2_put_NavTree_Stub		IZcPpPalette2_put_NavTree_Stub
#endif //#ifndef IAcPpPalette2_put_NavTree_Stub

#ifndef IAcPpPaletteEvents
#define IAcPpPaletteEvents		IZcPpPaletteEvents
#endif //#ifndef IAcPpPaletteEvents

#ifndef IAcPpPaletteEventsVtbl
#define IAcPpPaletteEventsVtbl		IZcPpPaletteEventsVtbl
#endif //#ifndef IAcPpPaletteEventsVtbl

#ifndef IAcPpPaletteEvents_AddRef
#define IAcPpPaletteEvents_AddRef		IZcPpPaletteEvents_AddRef
#endif //#ifndef IAcPpPaletteEvents_AddRef

#ifndef IAcPpPaletteEvents_OnNameChanged
#define IAcPpPaletteEvents_OnNameChanged		IZcPpPaletteEvents_OnNameChanged
#endif //#ifndef IAcPpPaletteEvents_OnNameChanged

#ifndef IAcPpPaletteEvents_OnNameChanged_Proxy
#define IAcPpPaletteEvents_OnNameChanged_Proxy		IZcPpPaletteEvents_OnNameChanged_Proxy
#endif //#ifndef IAcPpPaletteEvents_OnNameChanged_Proxy

#ifndef IAcPpPaletteEvents_OnNameChanged_Stub
#define IAcPpPaletteEvents_OnNameChanged_Stub		IZcPpPaletteEvents_OnNameChanged_Stub
#endif //#ifndef IAcPpPaletteEvents_OnNameChanged_Stub

#ifndef IAcPpPaletteEvents_OnSelectionChanged
#define IAcPpPaletteEvents_OnSelectionChanged		IZcPpPaletteEvents_OnSelectionChanged
#endif //#ifndef IAcPpPaletteEvents_OnSelectionChanged

#ifndef IAcPpPaletteEvents_OnSelectionChanged_Proxy
#define IAcPpPaletteEvents_OnSelectionChanged_Proxy		IZcPpPaletteEvents_OnSelectionChanged_Proxy
#endif //#ifndef IAcPpPaletteEvents_OnSelectionChanged_Proxy

#ifndef IAcPpPaletteEvents_OnSelectionChanged_Stub
#define IAcPpPaletteEvents_OnSelectionChanged_Stub		IZcPpPaletteEvents_OnSelectionChanged_Stub
#endif //#ifndef IAcPpPaletteEvents_OnSelectionChanged_Stub

#ifndef IAcPpPaletteEvents_QueryInterface
#define IAcPpPaletteEvents_QueryInterface		IZcPpPaletteEvents_QueryInterface
#endif //#ifndef IAcPpPaletteEvents_QueryInterface

#ifndef IAcPpPaletteEvents_Release
#define IAcPpPaletteEvents_Release		IZcPpPaletteEvents_Release
#endif //#ifndef IAcPpPaletteEvents_Release

#ifndef IAcPpPaletteSet
#define IAcPpPaletteSet		IZcPpPaletteSet
#endif //#ifndef IAcPpPaletteSet

#ifndef IAcPpPaletteSetEvents
#define IAcPpPaletteSetEvents		IZcPpPaletteSetEvents
#endif //#ifndef IAcPpPaletteSetEvents

#ifndef IAcPpPaletteSetEventsVtbl
#define IAcPpPaletteSetEventsVtbl		IZcPpPaletteSetEventsVtbl
#endif //#ifndef IAcPpPaletteSetEventsVtbl

#ifndef IAcPpPaletteSetEvents_AddRef
#define IAcPpPaletteSetEvents_AddRef		IZcPpPaletteSetEvents_AddRef
#endif //#ifndef IAcPpPaletteSetEvents_AddRef

#ifndef IAcPpPaletteSetEvents_OnPaletteActivated
#define IAcPpPaletteSetEvents_OnPaletteActivated		IZcPpPaletteSetEvents_OnPaletteActivated
#endif //#ifndef IAcPpPaletteSetEvents_OnPaletteActivated

#ifndef IAcPpPaletteSetEvents_OnPaletteActivated_Proxy
#define IAcPpPaletteSetEvents_OnPaletteActivated_Proxy		IZcPpPaletteSetEvents_OnPaletteActivated_Proxy
#endif //#ifndef IAcPpPaletteSetEvents_OnPaletteActivated_Proxy

#ifndef IAcPpPaletteSetEvents_OnPaletteActivated_Stub
#define IAcPpPaletteSetEvents_OnPaletteActivated_Stub		IZcPpPaletteSetEvents_OnPaletteActivated_Stub
#endif //#ifndef IAcPpPaletteSetEvents_OnPaletteActivated_Stub

#ifndef IAcPpPaletteSetEvents_OnPaletteAdded
#define IAcPpPaletteSetEvents_OnPaletteAdded		IZcPpPaletteSetEvents_OnPaletteAdded
#endif //#ifndef IAcPpPaletteSetEvents_OnPaletteAdded

#ifndef IAcPpPaletteSetEvents_OnPaletteAdded_Proxy
#define IAcPpPaletteSetEvents_OnPaletteAdded_Proxy		IZcPpPaletteSetEvents_OnPaletteAdded_Proxy
#endif //#ifndef IAcPpPaletteSetEvents_OnPaletteAdded_Proxy

#ifndef IAcPpPaletteSetEvents_OnPaletteAdded_Stub
#define IAcPpPaletteSetEvents_OnPaletteAdded_Stub		IZcPpPaletteSetEvents_OnPaletteAdded_Stub
#endif //#ifndef IAcPpPaletteSetEvents_OnPaletteAdded_Stub

#ifndef IAcPpPaletteSetEvents_OnPaletteDeActivated
#define IAcPpPaletteSetEvents_OnPaletteDeActivated		IZcPpPaletteSetEvents_OnPaletteDeActivated
#endif //#ifndef IAcPpPaletteSetEvents_OnPaletteDeActivated

#ifndef IAcPpPaletteSetEvents_OnPaletteDeActivated_Proxy
#define IAcPpPaletteSetEvents_OnPaletteDeActivated_Proxy		IZcPpPaletteSetEvents_OnPaletteDeActivated_Proxy
#endif //#ifndef IAcPpPaletteSetEvents_OnPaletteDeActivated_Proxy

#ifndef IAcPpPaletteSetEvents_OnPaletteDeActivated_Stub
#define IAcPpPaletteSetEvents_OnPaletteDeActivated_Stub		IZcPpPaletteSetEvents_OnPaletteDeActivated_Stub
#endif //#ifndef IAcPpPaletteSetEvents_OnPaletteDeActivated_Stub

#ifndef IAcPpPaletteSetEvents_OnPaletteDeleted
#define IAcPpPaletteSetEvents_OnPaletteDeleted		IZcPpPaletteSetEvents_OnPaletteDeleted
#endif //#ifndef IAcPpPaletteSetEvents_OnPaletteDeleted

#ifndef IAcPpPaletteSetEvents_OnPaletteDeleted_Proxy
#define IAcPpPaletteSetEvents_OnPaletteDeleted_Proxy		IZcPpPaletteSetEvents_OnPaletteDeleted_Proxy
#endif //#ifndef IAcPpPaletteSetEvents_OnPaletteDeleted_Proxy

#ifndef IAcPpPaletteSetEvents_OnPaletteDeleted_Stub
#define IAcPpPaletteSetEvents_OnPaletteDeleted_Stub		IZcPpPaletteSetEvents_OnPaletteDeleted_Stub
#endif //#ifndef IAcPpPaletteSetEvents_OnPaletteDeleted_Stub

#ifndef IAcPpPaletteSetEvents_OnSelectionChanged
#define IAcPpPaletteSetEvents_OnSelectionChanged		IZcPpPaletteSetEvents_OnSelectionChanged
#endif //#ifndef IAcPpPaletteSetEvents_OnSelectionChanged

#ifndef IAcPpPaletteSetEvents_OnSelectionChanged_Proxy
#define IAcPpPaletteSetEvents_OnSelectionChanged_Proxy		IZcPpPaletteSetEvents_OnSelectionChanged_Proxy
#endif //#ifndef IAcPpPaletteSetEvents_OnSelectionChanged_Proxy

#ifndef IAcPpPaletteSetEvents_OnSelectionChanged_Stub
#define IAcPpPaletteSetEvents_OnSelectionChanged_Stub		IZcPpPaletteSetEvents_OnSelectionChanged_Stub
#endif //#ifndef IAcPpPaletteSetEvents_OnSelectionChanged_Stub

#ifndef IAcPpPaletteSetEvents_OnVisibilityChanged
#define IAcPpPaletteSetEvents_OnVisibilityChanged		IZcPpPaletteSetEvents_OnVisibilityChanged
#endif //#ifndef IAcPpPaletteSetEvents_OnVisibilityChanged

#ifndef IAcPpPaletteSetEvents_OnVisibilityChanged_Proxy
#define IAcPpPaletteSetEvents_OnVisibilityChanged_Proxy		IZcPpPaletteSetEvents_OnVisibilityChanged_Proxy
#endif //#ifndef IAcPpPaletteSetEvents_OnVisibilityChanged_Proxy

#ifndef IAcPpPaletteSetEvents_OnVisibilityChanged_Stub
#define IAcPpPaletteSetEvents_OnVisibilityChanged_Stub		IZcPpPaletteSetEvents_OnVisibilityChanged_Stub
#endif //#ifndef IAcPpPaletteSetEvents_OnVisibilityChanged_Stub

#ifndef IAcPpPaletteSetEvents_QueryInterface
#define IAcPpPaletteSetEvents_QueryInterface		IZcPpPaletteSetEvents_QueryInterface
#endif //#ifndef IAcPpPaletteSetEvents_QueryInterface

#ifndef IAcPpPaletteSetEvents_Release
#define IAcPpPaletteSetEvents_Release		IZcPpPaletteSetEvents_Release
#endif //#ifndef IAcPpPaletteSetEvents_Release

#ifndef IAcPpPaletteSetVtbl
#define IAcPpPaletteSetVtbl		IZcPpPaletteSetVtbl
#endif //#ifndef IAcPpPaletteSetVtbl

#ifndef IAcPpPaletteSet_ActivatePalette
#define IAcPpPaletteSet_ActivatePalette		IZcPpPaletteSet_ActivatePalette
#endif //#ifndef IAcPpPaletteSet_ActivatePalette

#ifndef IAcPpPaletteSet_ActivatePalette_Proxy
#define IAcPpPaletteSet_ActivatePalette_Proxy		IZcPpPaletteSet_ActivatePalette_Proxy
#endif //#ifndef IAcPpPaletteSet_ActivatePalette_Proxy

#ifndef IAcPpPaletteSet_ActivatePalette_Stub
#define IAcPpPaletteSet_ActivatePalette_Stub		IZcPpPaletteSet_ActivatePalette_Stub
#endif //#ifndef IAcPpPaletteSet_ActivatePalette_Stub

#ifndef IAcPpPaletteSet_AddPalette
#define IAcPpPaletteSet_AddPalette		IZcPpPaletteSet_AddPalette
#endif //#ifndef IAcPpPaletteSet_AddPalette

#ifndef IAcPpPaletteSet_AddPalette_Proxy
#define IAcPpPaletteSet_AddPalette_Proxy		IZcPpPaletteSet_AddPalette_Proxy
#endif //#ifndef IAcPpPaletteSet_AddPalette_Proxy

#ifndef IAcPpPaletteSet_AddPalette_Stub
#define IAcPpPaletteSet_AddPalette_Stub		IZcPpPaletteSet_AddPalette_Stub
#endif //#ifndef IAcPpPaletteSet_AddPalette_Stub

#ifndef IAcPpPaletteSet_AddRef
#define IAcPpPaletteSet_AddRef		IZcPpPaletteSet_AddRef
#endif //#ifndef IAcPpPaletteSet_AddRef

#ifndef IAcPpPaletteSet_DeletePalette
#define IAcPpPaletteSet_DeletePalette		IZcPpPaletteSet_DeletePalette
#endif //#ifndef IAcPpPaletteSet_DeletePalette

#ifndef IAcPpPaletteSet_DeletePalette_Proxy
#define IAcPpPaletteSet_DeletePalette_Proxy		IZcPpPaletteSet_DeletePalette_Proxy
#endif //#ifndef IAcPpPaletteSet_DeletePalette_Proxy

#ifndef IAcPpPaletteSet_DeletePalette_Stub
#define IAcPpPaletteSet_DeletePalette_Stub		IZcPpPaletteSet_DeletePalette_Stub
#endif //#ifndef IAcPpPaletteSet_DeletePalette_Stub

#ifndef IAcPpPaletteSet_GetDockingRect
#define IAcPpPaletteSet_GetDockingRect		IZcPpPaletteSet_GetDockingRect
#endif //#ifndef IAcPpPaletteSet_GetDockingRect

#ifndef IAcPpPaletteSet_GetDockingRect_Proxy
#define IAcPpPaletteSet_GetDockingRect_Proxy		IZcPpPaletteSet_GetDockingRect_Proxy
#endif //#ifndef IAcPpPaletteSet_GetDockingRect_Proxy

#ifndef IAcPpPaletteSet_GetDockingRect_Stub
#define IAcPpPaletteSet_GetDockingRect_Stub		IZcPpPaletteSet_GetDockingRect_Stub
#endif //#ifndef IAcPpPaletteSet_GetDockingRect_Stub

#ifndef IAcPpPaletteSet_GetDockingState
#define IAcPpPaletteSet_GetDockingState		IZcPpPaletteSet_GetDockingState
#endif //#ifndef IAcPpPaletteSet_GetDockingState

#ifndef IAcPpPaletteSet_GetDockingState_Proxy
#define IAcPpPaletteSet_GetDockingState_Proxy		IZcPpPaletteSet_GetDockingState_Proxy
#endif //#ifndef IAcPpPaletteSet_GetDockingState_Proxy

#ifndef IAcPpPaletteSet_GetDockingState_Stub
#define IAcPpPaletteSet_GetDockingState_Stub		IZcPpPaletteSet_GetDockingState_Stub
#endif //#ifndef IAcPpPaletteSet_GetDockingState_Stub

#ifndef IAcPpPaletteSet_GetFloatingRect
#define IAcPpPaletteSet_GetFloatingRect		IZcPpPaletteSet_GetFloatingRect
#endif //#ifndef IAcPpPaletteSet_GetFloatingRect

#ifndef IAcPpPaletteSet_GetFloatingRect_Proxy
#define IAcPpPaletteSet_GetFloatingRect_Proxy		IZcPpPaletteSet_GetFloatingRect_Proxy
#endif //#ifndef IAcPpPaletteSet_GetFloatingRect_Proxy

#ifndef IAcPpPaletteSet_GetFloatingRect_Stub
#define IAcPpPaletteSet_GetFloatingRect_Stub		IZcPpPaletteSet_GetFloatingRect_Stub
#endif //#ifndef IAcPpPaletteSet_GetFloatingRect_Stub

#ifndef IAcPpPaletteSet_GetPalette
#define IAcPpPaletteSet_GetPalette		IZcPpPaletteSet_GetPalette
#endif //#ifndef IAcPpPaletteSet_GetPalette

#ifndef IAcPpPaletteSet_GetPaletteByName
#define IAcPpPaletteSet_GetPaletteByName		IZcPpPaletteSet_GetPaletteByName
#endif //#ifndef IAcPpPaletteSet_GetPaletteByName

#ifndef IAcPpPaletteSet_GetPaletteByName_Proxy
#define IAcPpPaletteSet_GetPaletteByName_Proxy		IZcPpPaletteSet_GetPaletteByName_Proxy
#endif //#ifndef IAcPpPaletteSet_GetPaletteByName_Proxy

#ifndef IAcPpPaletteSet_GetPaletteByName_Stub
#define IAcPpPaletteSet_GetPaletteByName_Stub		IZcPpPaletteSet_GetPaletteByName_Stub
#endif //#ifndef IAcPpPaletteSet_GetPaletteByName_Stub

#ifndef IAcPpPaletteSet_GetPalette_Proxy
#define IAcPpPaletteSet_GetPalette_Proxy		IZcPpPaletteSet_GetPalette_Proxy
#endif //#ifndef IAcPpPaletteSet_GetPalette_Proxy

#ifndef IAcPpPaletteSet_GetPalette_Stub
#define IAcPpPaletteSet_GetPalette_Stub		IZcPpPaletteSet_GetPalette_Stub
#endif //#ifndef IAcPpPaletteSet_GetPalette_Stub

#ifndef IAcPpPaletteSet_InsertPalette
#define IAcPpPaletteSet_InsertPalette		IZcPpPaletteSet_InsertPalette
#endif //#ifndef IAcPpPaletteSet_InsertPalette

#ifndef IAcPpPaletteSet_InsertPalette_Proxy
#define IAcPpPaletteSet_InsertPalette_Proxy		IZcPpPaletteSet_InsertPalette_Proxy
#endif //#ifndef IAcPpPaletteSet_InsertPalette_Proxy

#ifndef IAcPpPaletteSet_InsertPalette_Stub
#define IAcPpPaletteSet_InsertPalette_Stub		IZcPpPaletteSet_InsertPalette_Stub
#endif //#ifndef IAcPpPaletteSet_InsertPalette_Stub

#ifndef IAcPpPaletteSet_QueryInterface
#define IAcPpPaletteSet_QueryInterface		IZcPpPaletteSet_QueryInterface
#endif //#ifndef IAcPpPaletteSet_QueryInterface

#ifndef IAcPpPaletteSet_Release
#define IAcPpPaletteSet_Release		IZcPpPaletteSet_Release
#endif //#ifndef IAcPpPaletteSet_Release

#ifndef IAcPpPaletteSet_SetDockingState
#define IAcPpPaletteSet_SetDockingState		IZcPpPaletteSet_SetDockingState
#endif //#ifndef IAcPpPaletteSet_SetDockingState

#ifndef IAcPpPaletteSet_SetDockingState_Proxy
#define IAcPpPaletteSet_SetDockingState_Proxy		IZcPpPaletteSet_SetDockingState_Proxy
#endif //#ifndef IAcPpPaletteSet_SetDockingState_Proxy

#ifndef IAcPpPaletteSet_SetDockingState_Stub
#define IAcPpPaletteSet_SetDockingState_Stub		IZcPpPaletteSet_SetDockingState_Stub
#endif //#ifndef IAcPpPaletteSet_SetDockingState_Stub

#ifndef IAcPpPaletteSet_get_CurrentIndex
#define IAcPpPaletteSet_get_CurrentIndex		IZcPpPaletteSet_get_CurrentIndex
#endif //#ifndef IAcPpPaletteSet_get_CurrentIndex

#ifndef IAcPpPaletteSet_get_CurrentIndex_Proxy
#define IAcPpPaletteSet_get_CurrentIndex_Proxy		IZcPpPaletteSet_get_CurrentIndex_Proxy
#endif //#ifndef IAcPpPaletteSet_get_CurrentIndex_Proxy

#ifndef IAcPpPaletteSet_get_CurrentIndex_Stub
#define IAcPpPaletteSet_get_CurrentIndex_Stub		IZcPpPaletteSet_get_CurrentIndex_Stub
#endif //#ifndef IAcPpPaletteSet_get_CurrentIndex_Stub

#ifndef IAcPpPaletteSet_get_PaletteCount
#define IAcPpPaletteSet_get_PaletteCount		IZcPpPaletteSet_get_PaletteCount
#endif //#ifndef IAcPpPaletteSet_get_PaletteCount

#ifndef IAcPpPaletteSet_get_PaletteCount_Proxy
#define IAcPpPaletteSet_get_PaletteCount_Proxy		IZcPpPaletteSet_get_PaletteCount_Proxy
#endif //#ifndef IAcPpPaletteSet_get_PaletteCount_Proxy

#ifndef IAcPpPaletteSet_get_PaletteCount_Stub
#define IAcPpPaletteSet_get_PaletteCount_Stub		IZcPpPaletteSet_get_PaletteCount_Stub
#endif //#ifndef IAcPpPaletteSet_get_PaletteCount_Stub

#ifndef IAcPpPaletteSet_get_Visibility
#define IAcPpPaletteSet_get_Visibility		IZcPpPaletteSet_get_Visibility
#endif //#ifndef IAcPpPaletteSet_get_Visibility

#ifndef IAcPpPaletteSet_get_Visibility_Proxy
#define IAcPpPaletteSet_get_Visibility_Proxy		IZcPpPaletteSet_get_Visibility_Proxy
#endif //#ifndef IAcPpPaletteSet_get_Visibility_Proxy

#ifndef IAcPpPaletteSet_get_Visibility_Stub
#define IAcPpPaletteSet_get_Visibility_Stub		IZcPpPaletteSet_get_Visibility_Stub
#endif //#ifndef IAcPpPaletteSet_get_Visibility_Stub

#ifndef IAcPpPaletteSet_put_Visibility
#define IAcPpPaletteSet_put_Visibility		IZcPpPaletteSet_put_Visibility
#endif //#ifndef IAcPpPaletteSet_put_Visibility

#ifndef IAcPpPaletteSet_put_Visibility_Proxy
#define IAcPpPaletteSet_put_Visibility_Proxy		IZcPpPaletteSet_put_Visibility_Proxy
#endif //#ifndef IAcPpPaletteSet_put_Visibility_Proxy

#ifndef IAcPpPaletteSet_put_Visibility_Stub
#define IAcPpPaletteSet_put_Visibility_Stub		IZcPpPaletteSet_put_Visibility_Stub
#endif //#ifndef IAcPpPaletteSet_put_Visibility_Stub

#ifndef IAcPpPaletteVtbl
#define IAcPpPaletteVtbl		IZcPpPaletteVtbl
#endif //#ifndef IAcPpPaletteVtbl

#ifndef IAcPpPalette_AddRef
#define IAcPpPalette_AddRef		IZcPpPalette_AddRef
#endif //#ifndef IAcPpPalette_AddRef

#ifndef IAcPpPalette_QueryInterface
#define IAcPpPalette_QueryInterface		IZcPpPalette_QueryInterface
#endif //#ifndef IAcPpPalette_QueryInterface

#ifndef IAcPpPalette_Release
#define IAcPpPalette_Release		IZcPpPalette_Release
#endif //#ifndef IAcPpPalette_Release

#ifndef IAcPpPalette_get_InspectorControl
#define IAcPpPalette_get_InspectorControl		IZcPpPalette_get_InspectorControl
#endif //#ifndef IAcPpPalette_get_InspectorControl

#ifndef IAcPpPalette_get_InspectorControl_Proxy
#define IAcPpPalette_get_InspectorControl_Proxy		IZcPpPalette_get_InspectorControl_Proxy
#endif //#ifndef IAcPpPalette_get_InspectorControl_Proxy

#ifndef IAcPpPalette_get_InspectorControl_Stub
#define IAcPpPalette_get_InspectorControl_Stub		IZcPpPalette_get_InspectorControl_Stub
#endif //#ifndef IAcPpPalette_get_InspectorControl_Stub

#ifndef IAcPpPalette_get_Name
#define IAcPpPalette_get_Name		IZcPpPalette_get_Name
#endif //#ifndef IAcPpPalette_get_Name

#ifndef IAcPpPalette_get_Name_Proxy
#define IAcPpPalette_get_Name_Proxy		IZcPpPalette_get_Name_Proxy
#endif //#ifndef IAcPpPalette_get_Name_Proxy

#ifndef IAcPpPalette_get_Name_Stub
#define IAcPpPalette_get_Name_Stub		IZcPpPalette_get_Name_Stub
#endif //#ifndef IAcPpPalette_get_Name_Stub

#ifndef IAcPpPalette_put_Name
#define IAcPpPalette_put_Name		IZcPpPalette_put_Name
#endif //#ifndef IAcPpPalette_put_Name

#ifndef IAcPpPalette_put_Name_Proxy
#define IAcPpPalette_put_Name_Proxy		IZcPpPalette_put_Name_Proxy
#endif //#ifndef IAcPpPalette_put_Name_Proxy

#ifndef IAcPpPalette_put_Name_Stub
#define IAcPpPalette_put_Name_Stub		IZcPpPalette_put_Name_Stub
#endif //#ifndef IAcPpPalette_put_Name_Stub

#ifndef IAcPpZcadInput
#define IAcPpZcadInput		IZcPpZcadInput
#endif //#ifndef IAcPpZcadInput

#ifndef IAcPpZcadInputVtbl
#define IAcPpZcadInputVtbl		IZcPpZcadInputVtbl
#endif //#ifndef IAcPpZcadInputVtbl

#ifndef IAcPpZcadInput_AddRef
#define IAcPpZcadInput_AddRef		IZcPpZcadInput_AddRef
#endif //#ifndef IAcPpZcadInput_AddRef

#ifndef IAcPpZcadInput_CancelPrompt
#define IAcPpZcadInput_CancelPrompt		IZcPpZcadInput_CancelPrompt
#endif //#ifndef IAcPpZcadInput_CancelPrompt

#ifndef IAcPpZcadInput_CancelPrompt_Proxy
#define IAcPpZcadInput_CancelPrompt_Proxy		IZcPpZcadInput_CancelPrompt_Proxy
#endif //#ifndef IAcPpZcadInput_CancelPrompt_Proxy

#ifndef IAcPpZcadInput_CancelPrompt_Stub
#define IAcPpZcadInput_CancelPrompt_Stub		IZcPpZcadInput_CancelPrompt_Stub
#endif //#ifndef IAcPpZcadInput_CancelPrompt_Stub

#ifndef IAcPpZcadInput_DoPrompt
#define IAcPpZcadInput_DoPrompt		IZcPpZcadInput_DoPrompt
#endif //#ifndef IAcPpZcadInput_DoPrompt

#ifndef IAcPpZcadInput_DoPrompt_Proxy
#define IAcPpZcadInput_DoPrompt_Proxy		IZcPpZcadInput_DoPrompt_Proxy
#endif //#ifndef IAcPpZcadInput_DoPrompt_Proxy

#ifndef IAcPpZcadInput_DoPrompt_Stub
#define IAcPpZcadInput_DoPrompt_Stub		IZcPpZcadInput_DoPrompt_Stub
#endif //#ifndef IAcPpZcadInput_DoPrompt_Stub

#ifndef IAcPpZcadInput_QueryInterface
#define IAcPpZcadInput_QueryInterface		IZcPpZcadInput_QueryInterface
#endif //#ifndef IAcPpZcadInput_QueryInterface

#ifndef IAcPpZcadInput_Release
#define IAcPpZcadInput_Release		IZcPpZcadInput_Release
#endif //#ifndef IAcPpZcadInput_Release

#ifndef IAcPpZcadInput_get_BasePoint
#define IAcPpZcadInput_get_BasePoint		IZcPpZcadInput_get_BasePoint
#endif //#ifndef IAcPpZcadInput_get_BasePoint

#ifndef IAcPpZcadInput_get_BasePoint_Proxy
#define IAcPpZcadInput_get_BasePoint_Proxy		IZcPpZcadInput_get_BasePoint_Proxy
#endif //#ifndef IAcPpZcadInput_get_BasePoint_Proxy

#ifndef IAcPpZcadInput_get_BasePoint_Stub
#define IAcPpZcadInput_get_BasePoint_Stub		IZcPpZcadInput_get_BasePoint_Stub
#endif //#ifndef IAcPpZcadInput_get_BasePoint_Stub

#ifndef IAcPpZcadInput_get_CrOnly
#define IAcPpZcadInput_get_CrOnly		IZcPpZcadInput_get_CrOnly
#endif //#ifndef IAcPpZcadInput_get_CrOnly

#ifndef IAcPpZcadInput_get_CrOnly_Proxy
#define IAcPpZcadInput_get_CrOnly_Proxy		IZcPpZcadInput_get_CrOnly_Proxy
#endif //#ifndef IAcPpZcadInput_get_CrOnly_Proxy

#ifndef IAcPpZcadInput_get_CrOnly_Stub
#define IAcPpZcadInput_get_CrOnly_Stub		IZcPpZcadInput_get_CrOnly_Stub
#endif //#ifndef IAcPpZcadInput_get_CrOnly_Stub

#ifndef IAcPpZcadInput_get_Document
#define IAcPpZcadInput_get_Document		IZcPpZcadInput_get_Document
#endif //#ifndef IAcPpZcadInput_get_Document

#ifndef IAcPpZcadInput_get_Document_Proxy
#define IAcPpZcadInput_get_Document_Proxy		IZcPpZcadInput_get_Document_Proxy
#endif //#ifndef IAcPpZcadInput_get_Document_Proxy

#ifndef IAcPpZcadInput_get_Document_Stub
#define IAcPpZcadInput_get_Document_Stub		IZcPpZcadInput_get_Document_Stub
#endif //#ifndef IAcPpZcadInput_get_Document_Stub

#ifndef IAcPpZcadInput_get_EnableNotification
#define IAcPpZcadInput_get_EnableNotification		IZcPpZcadInput_get_EnableNotification
#endif //#ifndef IAcPpZcadInput_get_EnableNotification

#ifndef IAcPpZcadInput_get_EnableNotification_Proxy
#define IAcPpZcadInput_get_EnableNotification_Proxy		IZcPpZcadInput_get_EnableNotification_Proxy
#endif //#ifndef IAcPpZcadInput_get_EnableNotification_Proxy

#ifndef IAcPpZcadInput_get_EnableNotification_Stub
#define IAcPpZcadInput_get_EnableNotification_Stub		IZcPpZcadInput_get_EnableNotification_Stub
#endif //#ifndef IAcPpZcadInput_get_EnableNotification_Stub

#ifndef IAcPpZcadInput_get_InitGetBit
#define IAcPpZcadInput_get_InitGetBit		IZcPpZcadInput_get_InitGetBit
#endif //#ifndef IAcPpZcadInput_get_InitGetBit

#ifndef IAcPpZcadInput_get_InitGetBit_Proxy
#define IAcPpZcadInput_get_InitGetBit_Proxy		IZcPpZcadInput_get_InitGetBit_Proxy
#endif //#ifndef IAcPpZcadInput_get_InitGetBit_Proxy

#ifndef IAcPpZcadInput_get_InitGetBit_Stub
#define IAcPpZcadInput_get_InitGetBit_Stub		IZcPpZcadInput_get_InitGetBit_Stub
#endif //#ifndef IAcPpZcadInput_get_InitGetBit_Stub

#ifndef IAcPpZcadInput_get_InitGetKword
#define IAcPpZcadInput_get_InitGetKword		IZcPpZcadInput_get_InitGetKword
#endif //#ifndef IAcPpZcadInput_get_InitGetKword

#ifndef IAcPpZcadInput_get_InitGetKword_Proxy
#define IAcPpZcadInput_get_InitGetKword_Proxy		IZcPpZcadInput_get_InitGetKword_Proxy
#endif //#ifndef IAcPpZcadInput_get_InitGetKword_Proxy

#ifndef IAcPpZcadInput_get_InitGetKword_Stub
#define IAcPpZcadInput_get_InitGetKword_Stub		IZcPpZcadInput_get_InitGetKword_Stub
#endif //#ifndef IAcPpZcadInput_get_InitGetKword_Stub

#ifndef IAcPpZcadInput_get_Prompt
#define IAcPpZcadInput_get_Prompt		IZcPpZcadInput_get_Prompt
#endif //#ifndef IAcPpZcadInput_get_Prompt

#ifndef IAcPpZcadInput_get_Prompt2
#define IAcPpZcadInput_get_Prompt2		IZcPpZcadInput_get_Prompt2
#endif //#ifndef IAcPpZcadInput_get_Prompt2

#ifndef IAcPpZcadInput_get_Prompt2_Proxy
#define IAcPpZcadInput_get_Prompt2_Proxy		IZcPpZcadInput_get_Prompt2_Proxy
#endif //#ifndef IAcPpZcadInput_get_Prompt2_Proxy

#ifndef IAcPpZcadInput_get_Prompt2_Stub
#define IAcPpZcadInput_get_Prompt2_Stub		IZcPpZcadInput_get_Prompt2_Stub
#endif //#ifndef IAcPpZcadInput_get_Prompt2_Stub

#ifndef IAcPpZcadInput_get_PromptType
#define IAcPpZcadInput_get_PromptType		IZcPpZcadInput_get_PromptType
#endif //#ifndef IAcPpZcadInput_get_PromptType

#ifndef IAcPpZcadInput_get_PromptType_Proxy
#define IAcPpZcadInput_get_PromptType_Proxy		IZcPpZcadInput_get_PromptType_Proxy
#endif //#ifndef IAcPpZcadInput_get_PromptType_Proxy

#ifndef IAcPpZcadInput_get_PromptType_Stub
#define IAcPpZcadInput_get_PromptType_Stub		IZcPpZcadInput_get_PromptType_Stub
#endif //#ifndef IAcPpZcadInput_get_PromptType_Stub

#ifndef IAcPpZcadInput_get_Prompt_Proxy
#define IAcPpZcadInput_get_Prompt_Proxy		IZcPpZcadInput_get_Prompt_Proxy
#endif //#ifndef IAcPpZcadInput_get_Prompt_Proxy

#ifndef IAcPpZcadInput_get_Prompt_Stub
#define IAcPpZcadInput_get_Prompt_Stub		IZcPpZcadInput_get_Prompt_Stub
#endif //#ifndef IAcPpZcadInput_get_Prompt_Stub

#ifndef IAcPpZcadInput_get_Status
#define IAcPpZcadInput_get_Status		IZcPpZcadInput_get_Status
#endif //#ifndef IAcPpZcadInput_get_Status

#ifndef IAcPpZcadInput_get_Status_Proxy
#define IAcPpZcadInput_get_Status_Proxy		IZcPpZcadInput_get_Status_Proxy
#endif //#ifndef IAcPpZcadInput_get_Status_Proxy

#ifndef IAcPpZcadInput_get_Status_Stub
#define IAcPpZcadInput_get_Status_Stub		IZcPpZcadInput_get_Status_Stub
#endif //#ifndef IAcPpZcadInput_get_Status_Stub

#ifndef IAcPpZcadInput_get_Value
#define IAcPpZcadInput_get_Value		IZcPpZcadInput_get_Value
#endif //#ifndef IAcPpZcadInput_get_Value

#ifndef IAcPpZcadInput_get_Value_Proxy
#define IAcPpZcadInput_get_Value_Proxy		IZcPpZcadInput_get_Value_Proxy
#endif //#ifndef IAcPpZcadInput_get_Value_Proxy

#ifndef IAcPpZcadInput_get_Value_Stub
#define IAcPpZcadInput_get_Value_Stub		IZcPpZcadInput_get_Value_Stub
#endif //#ifndef IAcPpZcadInput_get_Value_Stub

#ifndef IAcPpZcadInput_put_BasePoint
#define IAcPpZcadInput_put_BasePoint		IZcPpZcadInput_put_BasePoint
#endif //#ifndef IAcPpZcadInput_put_BasePoint

#ifndef IAcPpZcadInput_put_BasePoint_Proxy
#define IAcPpZcadInput_put_BasePoint_Proxy		IZcPpZcadInput_put_BasePoint_Proxy
#endif //#ifndef IAcPpZcadInput_put_BasePoint_Proxy

#ifndef IAcPpZcadInput_put_BasePoint_Stub
#define IAcPpZcadInput_put_BasePoint_Stub		IZcPpZcadInput_put_BasePoint_Stub
#endif //#ifndef IAcPpZcadInput_put_BasePoint_Stub

#ifndef IAcPpZcadInput_put_CrOnly
#define IAcPpZcadInput_put_CrOnly		IZcPpZcadInput_put_CrOnly
#endif //#ifndef IAcPpZcadInput_put_CrOnly

#ifndef IAcPpZcadInput_put_CrOnly_Proxy
#define IAcPpZcadInput_put_CrOnly_Proxy		IZcPpZcadInput_put_CrOnly_Proxy
#endif //#ifndef IAcPpZcadInput_put_CrOnly_Proxy

#ifndef IAcPpZcadInput_put_CrOnly_Stub
#define IAcPpZcadInput_put_CrOnly_Stub		IZcPpZcadInput_put_CrOnly_Stub
#endif //#ifndef IAcPpZcadInput_put_CrOnly_Stub

#ifndef IAcPpZcadInput_put_Document
#define IAcPpZcadInput_put_Document		IZcPpZcadInput_put_Document
#endif //#ifndef IAcPpZcadInput_put_Document

#ifndef IAcPpZcadInput_put_Document_Proxy
#define IAcPpZcadInput_put_Document_Proxy		IZcPpZcadInput_put_Document_Proxy
#endif //#ifndef IAcPpZcadInput_put_Document_Proxy

#ifndef IAcPpZcadInput_put_Document_Stub
#define IAcPpZcadInput_put_Document_Stub		IZcPpZcadInput_put_Document_Stub
#endif //#ifndef IAcPpZcadInput_put_Document_Stub

#ifndef IAcPpZcadInput_put_EnableNotification
#define IAcPpZcadInput_put_EnableNotification		IZcPpZcadInput_put_EnableNotification
#endif //#ifndef IAcPpZcadInput_put_EnableNotification

#ifndef IAcPpZcadInput_put_EnableNotification_Proxy
#define IAcPpZcadInput_put_EnableNotification_Proxy		IZcPpZcadInput_put_EnableNotification_Proxy
#endif //#ifndef IAcPpZcadInput_put_EnableNotification_Proxy

#ifndef IAcPpZcadInput_put_EnableNotification_Stub
#define IAcPpZcadInput_put_EnableNotification_Stub		IZcPpZcadInput_put_EnableNotification_Stub
#endif //#ifndef IAcPpZcadInput_put_EnableNotification_Stub

#ifndef IAcPpZcadInput_put_InitGetBit
#define IAcPpZcadInput_put_InitGetBit		IZcPpZcadInput_put_InitGetBit
#endif //#ifndef IAcPpZcadInput_put_InitGetBit

#ifndef IAcPpZcadInput_put_InitGetBit_Proxy
#define IAcPpZcadInput_put_InitGetBit_Proxy		IZcPpZcadInput_put_InitGetBit_Proxy
#endif //#ifndef IAcPpZcadInput_put_InitGetBit_Proxy

#ifndef IAcPpZcadInput_put_InitGetBit_Stub
#define IAcPpZcadInput_put_InitGetBit_Stub		IZcPpZcadInput_put_InitGetBit_Stub
#endif //#ifndef IAcPpZcadInput_put_InitGetBit_Stub

#ifndef IAcPpZcadInput_put_InitGetKword
#define IAcPpZcadInput_put_InitGetKword		IZcPpZcadInput_put_InitGetKword
#endif //#ifndef IAcPpZcadInput_put_InitGetKword

#ifndef IAcPpZcadInput_put_InitGetKword_Proxy
#define IAcPpZcadInput_put_InitGetKword_Proxy		IZcPpZcadInput_put_InitGetKword_Proxy
#endif //#ifndef IAcPpZcadInput_put_InitGetKword_Proxy

#ifndef IAcPpZcadInput_put_InitGetKword_Stub
#define IAcPpZcadInput_put_InitGetKword_Stub		IZcPpZcadInput_put_InitGetKword_Stub
#endif //#ifndef IAcPpZcadInput_put_InitGetKword_Stub

#ifndef IAcPpZcadInput_put_Prompt
#define IAcPpZcadInput_put_Prompt		IZcPpZcadInput_put_Prompt
#endif //#ifndef IAcPpZcadInput_put_Prompt

#ifndef IAcPpZcadInput_put_Prompt2
#define IAcPpZcadInput_put_Prompt2		IZcPpZcadInput_put_Prompt2
#endif //#ifndef IAcPpZcadInput_put_Prompt2

#ifndef IAcPpZcadInput_put_Prompt2_Proxy
#define IAcPpZcadInput_put_Prompt2_Proxy		IZcPpZcadInput_put_Prompt2_Proxy
#endif //#ifndef IAcPpZcadInput_put_Prompt2_Proxy

#ifndef IAcPpZcadInput_put_Prompt2_Stub
#define IAcPpZcadInput_put_Prompt2_Stub		IZcPpZcadInput_put_Prompt2_Stub
#endif //#ifndef IAcPpZcadInput_put_Prompt2_Stub

#ifndef IAcPpZcadInput_put_PromptType
#define IAcPpZcadInput_put_PromptType		IZcPpZcadInput_put_PromptType
#endif //#ifndef IAcPpZcadInput_put_PromptType

#ifndef IAcPpZcadInput_put_PromptType_Proxy
#define IAcPpZcadInput_put_PromptType_Proxy		IZcPpZcadInput_put_PromptType_Proxy
#endif //#ifndef IAcPpZcadInput_put_PromptType_Proxy

#ifndef IAcPpZcadInput_put_PromptType_Stub
#define IAcPpZcadInput_put_PromptType_Stub		IZcPpZcadInput_put_PromptType_Stub
#endif //#ifndef IAcPpZcadInput_put_PromptType_Stub

#ifndef IAcPpZcadInput_put_Prompt_Proxy
#define IAcPpZcadInput_put_Prompt_Proxy		IZcPpZcadInput_put_Prompt_Proxy
#endif //#ifndef IAcPpZcadInput_put_Prompt_Proxy

#ifndef IAcPpZcadInput_put_Prompt_Stub
#define IAcPpZcadInput_put_Prompt_Stub		IZcPpZcadInput_put_Prompt_Stub
#endif //#ifndef IAcPpZcadInput_put_Prompt_Stub

#ifndef IAcPpZcadInput_put_Status
#define IAcPpZcadInput_put_Status		IZcPpZcadInput_put_Status
#endif //#ifndef IAcPpZcadInput_put_Status

#ifndef IAcPpZcadInput_put_Status_Proxy
#define IAcPpZcadInput_put_Status_Proxy		IZcPpZcadInput_put_Status_Proxy
#endif //#ifndef IAcPpZcadInput_put_Status_Proxy

#ifndef IAcPpZcadInput_put_Status_Stub
#define IAcPpZcadInput_put_Status_Stub		IZcPpZcadInput_put_Status_Stub
#endif //#ifndef IAcPpZcadInput_put_Status_Stub

#ifndef IAcPpZcadInput_put_Value
#define IAcPpZcadInput_put_Value		IZcPpZcadInput_put_Value
#endif //#ifndef IAcPpZcadInput_put_Value

#ifndef IAcPpZcadInput_put_Value_Proxy
#define IAcPpZcadInput_put_Value_Proxy		IZcPpZcadInput_put_Value_Proxy
#endif //#ifndef IAcPpZcadInput_put_Value_Proxy

#ifndef IAcPpZcadInput_put_Value_Stub
#define IAcPpZcadInput_put_Value_Stub		IZcPpZcadInput_put_Value_Stub
#endif //#ifndef IAcPpZcadInput_put_Value_Stub

#ifndef IID_IAcPp
#define IID_IAcPp		IID_IZcPp
#endif //#ifndef IID_IAcPp

#ifndef IID_IAcPpAcadInput
#define IID_IAcPpAcadInput		IID_IZcPpZcadInput
#endif //#ifndef IID_IAcPpAcadInput

#ifndef IID_IAcPpNavTree
#define IID_IAcPpNavTree		IID_IZcPpNavTree
#endif //#ifndef IID_IAcPpNavTree

#ifndef IID_IAcPpNavTreeCmdBtn
#define IID_IAcPpNavTreeCmdBtn		IID_IZcPpNavTreeCmdBtn
#endif //#ifndef IID_IAcPpNavTreeCmdBtn

#ifndef IID_IAcPpNavTreeCmdBtnCollection
#define IID_IAcPpNavTreeCmdBtnCollection		IID_IZcPpNavTreeCmdBtnCollection
#endif //#ifndef IID_IAcPpNavTreeCmdBtnCollection

#ifndef IID_IAcPpNavTreeCmdBtnCollectionIter
#define IID_IAcPpNavTreeCmdBtnCollectionIter		IID_IZcPpNavTreeCmdBtnCollectionIter
#endif //#ifndef IID_IAcPpNavTreeCmdBtnCollectionIter

#ifndef IID_IAcPpNavTreeEvents
#define IID_IAcPpNavTreeEvents		IID_IZcPpNavTreeEvents
#endif //#ifndef IID_IAcPpNavTreeEvents

#ifndef IID_IAcPpNavTreeNode
#define IID_IAcPpNavTreeNode		IID_IZcPpNavTreeNode
#endif //#ifndef IID_IAcPpNavTreeNode

#ifndef IID_IAcPpNavTreeNodeCollection
#define IID_IAcPpNavTreeNodeCollection		IID_IZcPpNavTreeNodeCollection
#endif //#ifndef IID_IAcPpNavTreeNodeCollection

#ifndef IID_IAcPpNavTreeNodeCollectionIter
#define IID_IAcPpNavTreeNodeCollectionIter		IID_IZcPpNavTreeNodeCollectionIter
#endif //#ifndef IID_IAcPpNavTreeNodeCollectionIter

#ifndef IID_IAcPpPalette
#define IID_IAcPpPalette		IID_IZcPpPalette
#endif //#ifndef IID_IAcPpPalette

#ifndef IID_IAcPpPalette2
#define IID_IAcPpPalette2		IID_IZcPpPalette2
#endif //#ifndef IID_IAcPpPalette2

#ifndef IID_IAcPpPaletteEvents
#define IID_IAcPpPaletteEvents		IID_IZcPpPaletteEvents
#endif //#ifndef IID_IAcPpPaletteEvents

#ifndef IID_IAcPpPaletteSet
#define IID_IAcPpPaletteSet		IID_IZcPpPaletteSet
#endif //#ifndef IID_IAcPpPaletteSet

#ifndef IID_IAcPpPaletteSetEvents
#define IID_IAcPpPaletteSetEvents		IID_IZcPpPaletteSetEvents
#endif //#ifndef IID_IAcPpPaletteSetEvents

#ifndef IID_IAcPpZcadInput
#define IID_IAcPpZcadInput		IID_IZcPpZcadInput
#endif //#ifndef IID_IAcPpZcadInput

#ifndef LIBID_AcPpLib
#define LIBID_AcPpLib		LIBID_ZcPpLib
#endif //#ifndef LIBID_AcPpLib

#ifndef PpAcadInput
#define PpAcadInput		PpZcadInput
#endif //#ifndef PpAcadInput

#ifndef ZcPpAcadInput
#define ZcPpAcadInput		ZcPpZcadInput
#endif //#ifndef ZcPpAcadInput

#ifndef __AcPp
#define __AcPp		__ZcPp
#endif //#ifndef __AcPp

#ifndef __AcPpAcadInput_FWD_DEFINED__
#define __AcPpAcadInput_FWD_DEFINED__		__ZcPpZcadInput_FWD_DEFINED__
#endif //#ifndef __AcPpAcadInput_FWD_DEFINED__

#ifndef __AcPpLib_LIBRARY_DEFINED__
#define __AcPpLib_LIBRARY_DEFINED__		__ZcPpLib_LIBRARY_DEFINED__
#endif //#ifndef __AcPpLib_LIBRARY_DEFINED__

#ifndef __AcPpNavTreeNode_FWD_DEFINED__
#define __AcPpNavTreeNode_FWD_DEFINED__		__ZcPpNavTreeNode_FWD_DEFINED__
#endif //#ifndef __AcPpNavTreeNode_FWD_DEFINED__

#ifndef __AcPpNavTree_FWD_DEFINED__
#define __AcPpNavTree_FWD_DEFINED__		__ZcPpNavTree_FWD_DEFINED__
#endif //#ifndef __AcPpNavTree_FWD_DEFINED__

#ifndef __AcPpPalette2_FWD_DEFINED__
#define __AcPpPalette2_FWD_DEFINED__		__ZcPpPalette2_FWD_DEFINED__
#endif //#ifndef __AcPpPalette2_FWD_DEFINED__

#ifndef __AcPpPaletteSet_FWD_DEFINED__
#define __AcPpPaletteSet_FWD_DEFINED__		__ZcPpPaletteSet_FWD_DEFINED__
#endif //#ifndef __AcPpPaletteSet_FWD_DEFINED__

#ifndef __AcPpPalette_FWD_DEFINED__
#define __AcPpPalette_FWD_DEFINED__		__ZcPpPalette_FWD_DEFINED__
#endif //#ifndef __AcPpPalette_FWD_DEFINED__

#ifndef __AcPpZcadInput_FWD_DEFINED__
#define __AcPpZcadInput_FWD_DEFINED__		__ZcPpZcadInput_FWD_DEFINED__
#endif //#ifndef __AcPpZcadInput_FWD_DEFINED__

#ifndef __IAcPp
#define __IAcPp		__IZcPp
#endif //#ifndef __IAcPp

#ifndef __IAcPpAcadInput_FWD_DEFINED__
#define __IAcPpAcadInput_FWD_DEFINED__		__IZcPpZcadInput_FWD_DEFINED__
#endif //#ifndef __IAcPpAcadInput_FWD_DEFINED__

#ifndef __IAcPpAcadInput_INTERFACE_DEFINED__
#define __IAcPpAcadInput_INTERFACE_DEFINED__		__IZcPpZcadInput_INTERFACE_DEFINED__
#endif //#ifndef __IAcPpAcadInput_INTERFACE_DEFINED__

#ifndef __IAcPpNavTreeCmdBtnCollectionIter_FWD_DEFINED__
#define __IAcPpNavTreeCmdBtnCollectionIter_FWD_DEFINED__		__IZcPpNavTreeCmdBtnCollectionIter_FWD_DEFINED__
#endif //#ifndef __IAcPpNavTreeCmdBtnCollectionIter_FWD_DEFINED__

#ifndef __IAcPpNavTreeCmdBtnCollectionIter_INTERFACE_DEFINED__
#define __IAcPpNavTreeCmdBtnCollectionIter_INTERFACE_DEFINED__		__IZcPpNavTreeCmdBtnCollectionIter_INTERFACE_DEFINED__
#endif //#ifndef __IAcPpNavTreeCmdBtnCollectionIter_INTERFACE_DEFINED__

#ifndef __IAcPpNavTreeCmdBtnCollection_FWD_DEFINED__
#define __IAcPpNavTreeCmdBtnCollection_FWD_DEFINED__		__IZcPpNavTreeCmdBtnCollection_FWD_DEFINED__
#endif //#ifndef __IAcPpNavTreeCmdBtnCollection_FWD_DEFINED__

#ifndef __IAcPpNavTreeCmdBtnCollection_INTERFACE_DEFINED__
#define __IAcPpNavTreeCmdBtnCollection_INTERFACE_DEFINED__		__IZcPpNavTreeCmdBtnCollection_INTERFACE_DEFINED__
#endif //#ifndef __IAcPpNavTreeCmdBtnCollection_INTERFACE_DEFINED__

#ifndef __IAcPpNavTreeCmdBtn_FWD_DEFINED__
#define __IAcPpNavTreeCmdBtn_FWD_DEFINED__		__IZcPpNavTreeCmdBtn_FWD_DEFINED__
#endif //#ifndef __IAcPpNavTreeCmdBtn_FWD_DEFINED__

#ifndef __IAcPpNavTreeCmdBtn_INTERFACE_DEFINED__
#define __IAcPpNavTreeCmdBtn_INTERFACE_DEFINED__		__IZcPpNavTreeCmdBtn_INTERFACE_DEFINED__
#endif //#ifndef __IAcPpNavTreeCmdBtn_INTERFACE_DEFINED__

#ifndef __IAcPpNavTreeEvents_FWD_DEFINED__
#define __IAcPpNavTreeEvents_FWD_DEFINED__		__IZcPpNavTreeEvents_FWD_DEFINED__
#endif //#ifndef __IAcPpNavTreeEvents_FWD_DEFINED__

#ifndef __IAcPpNavTreeEvents_INTERFACE_DEFINED__
#define __IAcPpNavTreeEvents_INTERFACE_DEFINED__		__IZcPpNavTreeEvents_INTERFACE_DEFINED__
#endif //#ifndef __IAcPpNavTreeEvents_INTERFACE_DEFINED__

#ifndef __IAcPpNavTreeNodeCollectionIter_FWD_DEFINED__
#define __IAcPpNavTreeNodeCollectionIter_FWD_DEFINED__		__IZcPpNavTreeNodeCollectionIter_FWD_DEFINED__
#endif //#ifndef __IAcPpNavTreeNodeCollectionIter_FWD_DEFINED__

#ifndef __IAcPpNavTreeNodeCollectionIter_INTERFACE_DEFINED__
#define __IAcPpNavTreeNodeCollectionIter_INTERFACE_DEFINED__		__IZcPpNavTreeNodeCollectionIter_INTERFACE_DEFINED__
#endif //#ifndef __IAcPpNavTreeNodeCollectionIter_INTERFACE_DEFINED__

#ifndef __IAcPpNavTreeNodeCollection_FWD_DEFINED__
#define __IAcPpNavTreeNodeCollection_FWD_DEFINED__		__IZcPpNavTreeNodeCollection_FWD_DEFINED__
#endif //#ifndef __IAcPpNavTreeNodeCollection_FWD_DEFINED__

#ifndef __IAcPpNavTreeNodeCollection_INTERFACE_DEFINED__
#define __IAcPpNavTreeNodeCollection_INTERFACE_DEFINED__		__IZcPpNavTreeNodeCollection_INTERFACE_DEFINED__
#endif //#ifndef __IAcPpNavTreeNodeCollection_INTERFACE_DEFINED__

#ifndef __IAcPpNavTreeNode_FWD_DEFINED__
#define __IAcPpNavTreeNode_FWD_DEFINED__		__IZcPpNavTreeNode_FWD_DEFINED__
#endif //#ifndef __IAcPpNavTreeNode_FWD_DEFINED__

#ifndef __IAcPpNavTreeNode_INTERFACE_DEFINED__
#define __IAcPpNavTreeNode_INTERFACE_DEFINED__		__IZcPpNavTreeNode_INTERFACE_DEFINED__
#endif //#ifndef __IAcPpNavTreeNode_INTERFACE_DEFINED__

#ifndef __IAcPpNavTree_FWD_DEFINED__
#define __IAcPpNavTree_FWD_DEFINED__		__IZcPpNavTree_FWD_DEFINED__
#endif //#ifndef __IAcPpNavTree_FWD_DEFINED__

#ifndef __IAcPpNavTree_INTERFACE_DEFINED__
#define __IAcPpNavTree_INTERFACE_DEFINED__		__IZcPpNavTree_INTERFACE_DEFINED__
#endif //#ifndef __IAcPpNavTree_INTERFACE_DEFINED__

#ifndef __IAcPpPalette2_FWD_DEFINED__
#define __IAcPpPalette2_FWD_DEFINED__		__IZcPpPalette2_FWD_DEFINED__
#endif //#ifndef __IAcPpPalette2_FWD_DEFINED__

#ifndef __IAcPpPalette2_INTERFACE_DEFINED__
#define __IAcPpPalette2_INTERFACE_DEFINED__		__IZcPpPalette2_INTERFACE_DEFINED__
#endif //#ifndef __IAcPpPalette2_INTERFACE_DEFINED__

#ifndef __IAcPpPaletteEvents_FWD_DEFINED__
#define __IAcPpPaletteEvents_FWD_DEFINED__		__IZcPpPaletteEvents_FWD_DEFINED__
#endif //#ifndef __IAcPpPaletteEvents_FWD_DEFINED__

#ifndef __IAcPpPaletteEvents_INTERFACE_DEFINED__
#define __IAcPpPaletteEvents_INTERFACE_DEFINED__		__IZcPpPaletteEvents_INTERFACE_DEFINED__
#endif //#ifndef __IAcPpPaletteEvents_INTERFACE_DEFINED__

#ifndef __IAcPpPaletteSetEvents_FWD_DEFINED__
#define __IAcPpPaletteSetEvents_FWD_DEFINED__		__IZcPpPaletteSetEvents_FWD_DEFINED__
#endif //#ifndef __IAcPpPaletteSetEvents_FWD_DEFINED__

#ifndef __IAcPpPaletteSetEvents_INTERFACE_DEFINED__
#define __IAcPpPaletteSetEvents_INTERFACE_DEFINED__		__IZcPpPaletteSetEvents_INTERFACE_DEFINED__
#endif //#ifndef __IAcPpPaletteSetEvents_INTERFACE_DEFINED__

#ifndef __IAcPpPaletteSet_FWD_DEFINED__
#define __IAcPpPaletteSet_FWD_DEFINED__		__IZcPpPaletteSet_FWD_DEFINED__
#endif //#ifndef __IAcPpPaletteSet_FWD_DEFINED__

#ifndef __IAcPpPaletteSet_INTERFACE_DEFINED__
#define __IAcPpPaletteSet_INTERFACE_DEFINED__		__IZcPpPaletteSet_INTERFACE_DEFINED__
#endif //#ifndef __IAcPpPaletteSet_INTERFACE_DEFINED__

#ifndef __IAcPpPalette_FWD_DEFINED__
#define __IAcPpPalette_FWD_DEFINED__		__IZcPpPalette_FWD_DEFINED__
#endif //#ifndef __IAcPpPalette_FWD_DEFINED__

#ifndef __IAcPpPalette_INTERFACE_DEFINED__
#define __IAcPpPalette_INTERFACE_DEFINED__		__IZcPpPalette_INTERFACE_DEFINED__
#endif //#ifndef __IAcPpPalette_INTERFACE_DEFINED__

#ifndef __IAcPpZcadInput_FWD_DEFINED__
#define __IAcPpZcadInput_FWD_DEFINED__		__IZcPpZcadInput_FWD_DEFINED__
#endif //#ifndef __IAcPpZcadInput_FWD_DEFINED__

#ifndef __IAcPpZcadInput_INTERFACE_DEFINED__
#define __IAcPpZcadInput_INTERFACE_DEFINED__		__IZcPpZcadInput_INTERFACE_DEFINED__
#endif //#ifndef __IAcPpZcadInput_INTERFACE_DEFINED__

#ifndef __MIDL_itf_AcPp_0000_v0_0_c_ifspec
#define __MIDL_itf_AcPp_0000_v0_0_c_ifspec		__MIDL_itf_ZcPp_0000_v0_0_c_ifspec
#endif //#ifndef __MIDL_itf_AcPp_0000_v0_0_c_ifspec

#ifndef __MIDL_itf_AcPp_0000_v0_0_s_ifspec
#define __MIDL_itf_AcPp_0000_v0_0_s_ifspec		__MIDL_itf_ZcPp_0000_v0_0_s_ifspec
#endif //#ifndef __MIDL_itf_AcPp_0000_v0_0_s_ifspec

#endif //#ifndef __ACPP_H__
